/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#ifndef PYPTO_CODEGEN_CCE_CCE_CODEGEN_H_
#define PYPTO_CODEGEN_CCE_CCE_CODEGEN_H_

#include <cstdint>
#include <map>
#include <optional>
#include <set>
#include <sstream>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

#include "backend/common/backend.h"
#include "codegen/cce/code_context.h"
#include "codegen/cce/code_emitter.h"
#include "codegen/cce/type_converter.h"
#include "codegen/codegen_base.h"
#include "core/dtype.h"
#include "ir/expr.h"
#include "ir/function.h"
#include "ir/pipe.h"
#include "ir/program.h"
#include "ir/scalar_expr.h"
#include "ir/scalar_expr_ops.h"
#include "ir/stmt.h"
#include "ir/type.h"

namespace pypto {

namespace codegen {

/// Tile definition collected from a block.make_tile source.
/// Used by CCECodegen to emit section-aware prologue declarations.
struct TileDef {
    ir::VarPtr var;
    ir::TileTypePtr tile_type;
    std::optional<ir::SectionKind> def_section; ///< nullopt = defined outside any section (shared)
};

/// Tensor definition collected from block.load/store access windows.
/// Mirrors TileDef: drives section-aware GlobalTensor declarations in the prologue.
/// tensor_type and the base pointer are derived from `var` at emit time (not stored):
/// tensor_type = ir::As<ir::TensorType>(var->GetType()); the base pointer is the view's
/// source pointer (ptr.make_tensor) or "<name>_ptr" for a plain tensor parameter.
struct TensorDef {
    ir::VarPtr var;                             ///< tensor variable (parameter or ptr.make_tensor view)
    std::vector<ir::ExprPtr> access_shape;      ///< access window shape (tile-derived) from load/store
    std::optional<ir::SectionKind> def_section; ///< nullopt = used outside any section (shared)
    std::optional<std::vector<int>> tile_dims;  ///< tile_dims kwarg for strided views (if any)
    bool is_dn = false;                         ///< loaded with layout="dn" (needs Layout::DN)
};

/**
 * \brief CCE code generator for converting PyPTO IR to pto-isa C++ code
 *
 * CCECodegen traverses the IR using the visitor pattern and generates
 * compilable C++ code using pto-isa instructions. It handles:
 * - Function prologue (signature, argument unpacking, type definitions)
 * - Function body (block operations, sync operations, control flow)
 * - Type conversions and memory management
 */
class CCECodegen : public CodegenBase {
protected:
    using CodegenBase::VisitExpr_;
    using CodegenBase::VisitStmt_;

public:
    /** \brief Default constructor (backend is always CCE) */
    CCECodegen();

    /**
     * \brief Generate a single C++ file from a PyPTO IR Program (MIX mode)
     *
     * Runs IR passes (LowerBreakContinue ->ConvertToSSA ->ConstFoldAndSimplify),
     * then generates a single __global__ AICORE kernel with:
     * - PTO-style function signature
     * - Section-aware tile declarations (#if __DAV_CUBE__ / __DAV_VEC__)
     * - constexpr for compile-time constants
     * - FFTS support for cross-core sync
     *
     * \param program The IR Program to generate code for
     * \return Generated C++ code as a single string
     */
    [[nodiscard]] std::string GenerateSingle(const ir::ProgramPtr& program, const std::string& arch = "a3");

    /**
     * \brief Tiling struct headers generated by the last GenerateSingle call.
     *
     * Maps header filename (e.g. "OpTiling_tiling.h") to its content (a `#pragma once`
     * guarded `struct <ClassName> { ... };`). The kernel.cpp `#include`s these by name;
     * the caller (jit.py) writes them next to kernel.cpp in the build dir.
     */
    [[nodiscard]] const std::map<std::string, std::string>& GetTilingHeaders() const { return tiling_headers_; }

    // CodegenBase interface (unified API for operator codegen callbacks)
    [[nodiscard]] std::string GetCurrentResultTarget() const override { return current_target_var_; }
    void Emit(const std::string& line) override;
    std::string GetExprAsCode(const ir::ExprPtr& expr) override;
    [[nodiscard]] std::string GetTypeString(const ir::DataType& dtype) const override;
    /// True when currently generating code inside a VF section (CCE __VEC_SCOPE__).
    [[nodiscard]] bool IsInVFSection() const
    {
        return current_section_kind_.has_value() && *current_section_kind_ == ir::SectionKind::VF;
    }
    int GetTileOffsetCounter() { return tile_offset_counter_++; }
    /// Resolve a VF tile expr (plain tile or `tile[offset]`) to its `__ubuf__` pointer, typed as the
    /// tile element and hoisted before `__VEC_SCOPE__`. A `tile[offset]` load reuses the rvalue
    /// `(vf_tile_ptr_N + off)`; otherwise a `vf_tile_ptr_N` is declared once and cached. With
    /// `is_post_update`, even a `tile[offset]` materialises a cursor the intrinsic advances in place.
    std::string GetOrCreateVFTilePtr(const ir::ExprPtr& expr, bool is_post_update = false);
    int64_t GetConstIntValue(const ir::ExprPtr& expr) override;
    std::string GetVarName(const ir::VarPtr& var) override;

    const TypeConverter& GetTypeConverter() const { return type_converter_; }

    /** \brief Get the target architecture */
    const std::string& GetArch() const { return arch_; }

    /** \brief Get current section kind (Cube or Vector), nullopt if not in any section */
    std::optional<ir::SectionKind> GetCurrentSectionKind() const { return current_section_kind_; }

    /** \brief Check if currently generating code inside a Cube section */
    bool IsInCubeSection() const
    {
        return current_section_kind_.has_value() && *current_section_kind_ == ir::SectionKind::Cube;
    }

    /** \brief Get the base address of a tile variable (from TASSIGN in prologue) */
    std::string GetTileAddress(const std::string& tile_name) const
    {
        auto it = tile_addresses_.find(tile_name);
        if (it != tile_addresses_.end())
            return it->second;
        return "0x0";
    }

    /** \brief Register valid-shape C++ code strings for a tile at emit-time.
     *
     * Called from set_validshape codegen when each SetValidShape line is emitted.
     * row_code / col_code are already-resolved C++ expression strings.
     * Because set_validshape is guaranteed to precede any load/store that uses the
     * same tile, the entry is always present when load/store codegen queries it.
     */
    void RegisterTileEmitShape(const std::string& tile_cpp_name, const std::string& row_code,
                               const std::string& col_code)
    {
        tile_emit_shape_[tile_cpp_name] = {row_code, col_code};
    }

    /** \brief Look up the emit-time valid-shape for a tile (used by load and store). */
    std::optional<std::pair<std::string, std::string>> LookupTileEmitShape(const std::string& tile_cpp_name) const
    {
        auto it = tile_emit_shape_.find(tile_cpp_name);
        if (it != tile_emit_shape_.end())
            return it->second;
        return std::nullopt;
    }

    /**
     * \brief Compute offset from IR tensor shape (for single-file mode without Tensor struct)
     *
     * Computes row-major stride-based offset: off[0]*stride[0] + off[1]*stride[1] + ...
     * where stride[i] = product(shape[i+1..n-1])
     */
    std::string ComputeIRBasedOffset(const ir::TensorTypePtr& tensor_type, const ir::MakeTuplePtr& offsets);

    /**
     * \brief Register a tensor variable's underlying raw pointer (CCE-specific).
     *
     * Associates a tensor variable (parameter, ptr.make_tensor view, or iter_arg) with its
     * raw pointer expression. Used for GlobalTensor construction and TASSIGN address
     * computation in block.load/store. Same-key re-registration with a different value warns.
     */
    void RegisterPointer(const std::string& tensor_var_name, const std::string& ptr_name);

    /**
     * \brief Get pointer name for a variable (CCE-specific)
     */
    std::string GetPointer(const std::string& var_name);

    /**
     * \brief Check whether a raw pointer mapping has been registered (non-throwing).
     *
     * Distinguishes a tensor parameter / view (pointer already registered) from an
     * IfStmt phi return var (pointer not yet known).
     */
    [[nodiscard]] bool HasPointer(const std::string& var_name) const;

    /**
     * \brief Record that the named C++ variable holds a value of the given
     * struct type (e.g. "CubeCtx_slot_0" ->"CubeCtx"). Used so dynamic
     * GetItem on a struct-tuple-array can declare the hoisted array with
     * the correct C++ struct element type without resorting to decltype.
     */
    void RecordStructVarType(const std::string& var_name, const std::string& type_name)
    {
        if (!var_name.empty() && !type_name.empty())
            struct_var_to_type_name_[var_name] = type_name;
    }

    /**
     * \brief Check whether a PIPE_V mutex lock/unlock should be skipped.
     *
     * Returns true (skip) when arch is A5, pipe is PIPE_V, and all buf_ids
     * in the vector are only used by PIPE_V (no cross-pipe synchronization needed).
     */
    bool ShouldSkipVPipeMutex(ir::PipeType pipe, const std::vector<int>& buf_ids) const;

    /**
     * \brief Generate GlobalTensor type declaration and instance for a TensorDef.
     *
     * Emits shape type alias, stride type alias, GlobalTensor type alias, and instance
     * declaration. var_name, tensor_type and base pointer are derived from def.var; dn /
     * tile_dims come from def. Public so ptr.make_tensor codegen can emit a view in place.
     */
    void GenerateGlobalTensorTypeDeclaration(const TensorDef& def);

    /**
     * \brief Look up a prescanned TensorDef by its cce variable name (ptr.make_tensor views).
     *
     * Returns nullptr when the name was never accessed by a block.load/store (no declaration
     * needed). Populated by CollectTensorDefs during the prologue.
     */
    [[nodiscard]] const TensorDef* GetTensorDef(const std::string& name) const;

protected:
    // Override visitor methods for code generation - Statements
    void VisitStmt_(const ir::AssignStmtPtr& op) override;
    void VisitStmt_(const ir::EvalStmtPtr& op) override;
    void VisitStmt_(const ir::ReturnStmtPtr& op) override;
    void VisitStmt_(const ir::ForStmtPtr& op) override;
    void VisitStmt_(const ir::WhileStmtPtr& op) override;
    void VisitStmt_(const ir::IfStmtPtr& op) override;
    void VisitStmt_(const ir::YieldStmtPtr& op) override;
    void VisitStmt_(const ir::SectionStmtPtr& op) override;

    // Override visitor methods for code generation - Expressions
    // Leaf nodes
    void VisitExpr_(const ir::VarPtr& op) override;

    void VisitExpr_(const ir::ConstIntPtr& op) override;
    void VisitExpr_(const ir::ConstFloatPtr& op) override;
    void VisitExpr_(const ir::ConstBoolPtr& op) override;
    void VisitExpr_(const ir::CallPtr& op) override;
    void VisitExpr_(const ir::GetItemExprPtr& op) override;
    void VisitExpr_(const ir::MakeTuplePtr& op) override;

    // Binary operations
    void VisitExpr_(const ir::AddPtr& op) override;
    void VisitExpr_(const ir::SubPtr& op) override;
    void VisitExpr_(const ir::MulPtr& op) override;
    void VisitExpr_(const ir::FloorDivPtr& op) override;
    void VisitExpr_(const ir::FloorModPtr& op) override;
    void VisitExpr_(const ir::FloatDivPtr& op) override;
    void VisitExpr_(const ir::MinPtr& op) override;
    void VisitExpr_(const ir::MaxPtr& op) override;
    void VisitExpr_(const ir::PowPtr& op) override;
    void VisitExpr_(const ir::EqPtr& op) override;
    void VisitExpr_(const ir::NePtr& op) override;
    void VisitExpr_(const ir::LtPtr& op) override;
    void VisitExpr_(const ir::LePtr& op) override;
    void VisitExpr_(const ir::GtPtr& op) override;
    void VisitExpr_(const ir::GePtr& op) override;
    void VisitExpr_(const ir::AndPtr& op) override;
    void VisitExpr_(const ir::OrPtr& op) override;
    void VisitExpr_(const ir::XorPtr& op) override;
    void VisitExpr_(const ir::BitAndPtr& op) override;
    void VisitExpr_(const ir::BitOrPtr& op) override;
    void VisitExpr_(const ir::BitXorPtr& op) override;
    void VisitExpr_(const ir::BitShiftLeftPtr& op) override;
    void VisitExpr_(const ir::BitShiftRightPtr& op) override;

    // Unary operations
    void VisitExpr_(const ir::AbsPtr& op) override;
    void VisitExpr_(const ir::NegPtr& op) override;
    void VisitExpr_(const ir::NotPtr& op) override;
    void VisitExpr_(const ir::BitNotPtr& op) override;
    void VisitExpr_(const ir::CastPtr& op) override;

private:
    /**
     * \brief Extract yield variable names from an IR body without emitting code.
     *
     * Inspects the trailing YieldStmt in @p body (which may be a bare YieldStmt
     * or the last statement of a SeqStmts) and returns the resolved name for each
     * yielded value.  Handles Var, ConstInt, IterArg, and GetItemExpr on a tuple
     * (including inlined MakeTuple).  Returns an empty vector when any yield
     * value cannot be resolved.
     */
    std::vector<std::string> ExtractYieldNames(const ir::StmtPtr& body) const;
    std::optional<std::string> ResolveYieldName(const ir::ExprPtr& value) const;

    /**
     * \brief Emit yield-assignment code for if-stmt return variables.
     *
     * For each return variable, resolves the corresponding yield value from
     * @p target_names, emits a TASSIGN (Tile/Tuple) or scalar assignment, and
     * propagates pointer / tensor-struct mappings.  Clears yield_buffer_ when
     * done.
     */
    void EmitYieldAssignments(const std::vector<ir::VarPtr>& return_vars, const std::vector<std::string>& target_names);

    /**
     * \brief Emit full phi-style IfStmt codegen.
     *
     * Declares return variables before the if, emits then and else bodies, and
     * writes yield-assignment code in each branch.
     */
    void EmitFullPhiIf(const ir::IfStmtPtr& op);

    /**
     * \brief Generate function body
     *
     * Visits the function body statement to generate the main code.
     *
     * \param func The function to generate body for
     */
    void GenerateBody(const ir::FunctionPtr& func);

    /**
     * \brief Extract constant integer value from expression
     *
     * \param expr The expression (must be ConstInt)
     * \return The integer value
     */
    int64_t ExtractConstInt(const ir::ExprPtr& expr) const;

    /**
     * \brief Collect all TileType variables from function body
     *
     * Recursively traverses the statement tree to find all variables
     * with TileType that need Tile declarations in the prologue.
     *
     * \param stmt The statement to scan (typically func->body_)
     * \return Vector of (Var, TileType) pairs
     */
    std::vector<std::pair<ir::VarPtr, ir::TileTypePtr>> CollectTileVariables(const ir::StmtPtr& stmt);

    /// Collect one TensorDef per accessed tensor var from block.load/store access windows into
    /// tensor_defs_, keyed by cce var name (parameters and ptr.make_tensor views both collected;
    /// used for prologue param-tensor emission and in-place view emission at the make_tensor op).
    void CollectTensorDefs(const ir::FunctionPtr& func);

    /**
     * \brief Extract shape dimensions from shape expressions
     *
     * Converts a vector of shape expressions (assumed to be ConstInt)
     * into a vector of integer dimensions.
     *
     * \param shape_exprs Vector of shape expressions (ConstInt)
     * \return Vector of integer dimensions
     */
    std::vector<int64_t> ExtractShapeDimensions(const std::vector<ir::ExprPtr>& shape_exprs) const;

    /**
     * \brief Format address as hexadecimal string
     *
     * Converts an integer address to hex format for TASSIGN instructions.
     *
     * \param addr Address value
     * \return Hex string (e.g., "0x0", "0x10000")
     */
    std::string FormatAddressHex(int64_t addr);

    /**
     * \brief Emit one C++ `struct` definition per unique struct.create type name found in body.
     *
     * Deduplicates by struct type name (one definition per name).
     */
    void PreEmitStructTypes(const ir::StmtPtr& body);

    /**
     * \brief Emit `#include "<ClassName>_tiling.h"` for each tiling (TupleType) parameter
     *        and stash the corresponding `struct <ClassName> { ... };` header into
     *        tiling_headers_ for the caller to write out.
     *
     * Tiling params are lowered to a named TupleType whose field names + class name live
     * in the IRDebugInfo side table. Member types come from CppTypeForField.
     */
    void EmitTilingStructTypes(const ir::FunctionPtr& func);

    /**
     * \brief Emit the kernel-entry copy from the `<name>_ptr` GM pointer into the local
     *        struct `<name>` (cube: copy_data_align64 GM→struct; vector: copy GM→UB scratch,
     *        then copy_data_align64 UB→struct).
     */
    void EmitTilingStructCopy(const ir::FunctionPtr& func);

    /**
     * \brief Generate Tile type declaration and instance
     *
     * Emits type alias and instance declaration for a Tile variable.
     * Automatically extracts memref address from tile_type if present and emits TASSIGN.
     *
     * \param var_name Variable name for the tile
     * \param tile_type The TileType to generate declaration for (memref extracted automatically)
     */
    void GenerateTileTypeDeclaration(const std::string& var_name, const ir::TileTypePtr& tile_type);

    /**
     * \brief Generate PTO-style function signature and prologue for single-file mode
     *
     * Emits __global__ AICORE void func_name(__gm__ type* p, ...) with constexpr
     * scalars and section-aware tile declarations.
     */
    void GenerateSinglePrologue(const ir::FunctionPtr& func, bool has_cross_sync);
    void PreScanKernel(const ir::FunctionPtr& kernel_func);
    void PrepareBodyGeneration();

    bool DetectCrossCoreSyncOps(const ir::StmtPtr& stmt);

    // --- Phase 5: ForStmt helpers ---

    /**
     * \brief Register iteration arguments for a for-loop and emit their initialization.
     *
     * Handles alias propagation, cross-section safety, and pointer/struct inheritance.
     * Returns the sanitized names of each iter-arg for later yield assignment.
     */
    std::vector<std::string> RegisterForIterArgs(const ir::ForStmtPtr& op);
    void PropagateTupleIterArgs(const ir::ForStmtPtr& op);

    /**
     * \brief Emit yield-to-iter-arg assignments at the end of a for-loop body.
     *
     * Resolves aliases, detects self-assignments, and uses TASSIGN for tile transfers.
     */
    void EmitForYieldAssignments(const std::vector<std::string>& iter_arg_names);
    void RegisterForReturnVars(const ir::ForStmtPtr& op, const std::vector<std::string>& iter_arg_names);

    void EmitForLoopWithHoisting(const ir::ForStmtPtr& op, const std::string& loop_var_name,
                                 const std::vector<std::string>& iter_arg_names, const std::string& start,
                                 const std::string& stop, const std::string& step);

    // --- Phase 6: GenerateSinglePrologue helpers ---

    /**
     * \brief Emit the __global__ AICORE function signature and opening boilerplate.
     *
     * Collects dynamic dim variables, builds the parameter list, emits the opening
     * brace, registers dynamic dims, and emits FFTS setup if needed.
     */
    void EmitSingleFunctionSignature(const ir::FunctionPtr& func, bool has_cross_sync);

    /**
     * \brief Emit section-aware GlobalTensor declarations for single-file mode.
     *
     * Registers the C++ name (= tensor var name) and pointer ("<name>_ptr") for every
     * tensor parameter, collects TensorDefs, then emits them grouped by section.
     */
    void EmitSingleTensorDeclarations(const ir::FunctionPtr& func);
    void EmitSectionAwareTensors(const std::vector<TensorDef>& defs);

    /**
     * \brief Emit section-aware Tile declarations for single-file mode.
     */
    void EmitSingleTileDeclarations(const ir::FunctionPtr& func);

    void EmitSectionAwareTiles(const std::vector<TileDef>& tile_defs,
                               const std::vector<std::pair<ir::VarPtr, ir::VarPtr>>& deduped_aliases);
    void EmitDedupedTileAliases(const std::vector<TileDef>& tile_defs,
                                const std::vector<std::pair<ir::VarPtr, ir::VarPtr>>& deduped_aliases,
                                std::optional<ir::SectionKind> section);

    // --- Phase 7: GenerateGlobalTensorTypeDeclaration helpers ---

    /**
     * \brief Generate a fully static ND (row-major) pto::Stride<> string from physical dims.
     *
     * Pads to five slots with leading 1s. Used for the NZ physical fractal shape.
     */
    std::string GenerateSingleFileStrideType(const std::vector<int64_t>& dims) const;

    std::string BuildDynamicNZTensorDimArg(const ir::TensorTypePtr& tensor_type, size_t axis);

    std::string BuildDynamicNZShapeArg(const ir::TensorTypePtr& tensor_type, size_t axis,
                                       const std::optional<std::vector<ir::ExprPtr>>& access_shape);

    void AppendDynamicStrideGlobalTensorArgs(std::ostringstream& global_instance, const std::string& shape_type_name,
                                             const std::string& stride_type_name, const ir::TensorTypePtr& tensor_type,
                                             const std::vector<int64_t>& shape_dims,
                                             const std::optional<std::vector<int>>& tile_dims, bool is_dn);

    void EmitDynamicNZGlobalTensorDeclaration(const std::string& var_name, const ir::TensorTypePtr& tensor_type,
                                              const std::optional<std::string>& base_pointer,
                                              const std::optional<std::vector<ir::ExprPtr>>& access_shape,
                                              const std::string& element_type, const std::string& shape_type_name,
                                              const std::string& stride_type_name, const std::string& global_type_name);

    /**
     * \brief Emit the full GlobalTensor declaration for an NZ-layout tensor (static or dynamic).
     */
    void EmitNZGlobalTensorDeclaration(const TensorDef& def, const std::string& var_name,
                                       const ir::TensorTypePtr& tensor_type);

    std::string BuildGlobalTensorLayoutArg(const std::string& stride_type_name, const std::vector<int64_t>& shape_dims,
                                           bool is_dn) const;

    /**
     * \brief Emit the GlobalTensor instance declaration and register pointer/struct mappings.
     */
    void EmitGlobalTensorInstance(const std::string& var_name, const std::string& global_type_name,
                                  const std::string& shape_type_name, const std::string& stride_type_name,
                                  const ir::TensorTypePtr& tensor_type, const std::vector<int64_t>& shape_dims,
                                  const std::optional<std::vector<int>>& tile_dims, bool is_dn,
                                  const std::string& base_pointer);

    /**
     * \brief Clear the emit-time tile shape map before body generation.
     *
     * set_validshape is guaranteed to precede any load/store using the same tile,
     * so no pre-scan is needed.  Shape registration happens at emit-time via
     * RegisterTileEmitShape().  This function resets the map for each new function.
     *
     * \param body Unused ->kept for call-site compatibility.
     */
    void PreScanValidShapes();

    // Dual-mode context for expression visitor pattern
    std::string current_target_var_;              ///< INPUT: Assignment target variable name (for Call expressions)
    std::string current_expr_value_;              ///< OUTPUT: Inline C++ value for scalar / tile expressions
    ir::MakeTuplePtr current_tuple_;              ///< OUTPUT: underlying MakeTuple for tuple-typed expressions
    std::vector<std::string> yield_buffer_;       ///< Temporary storage for yielded values from loops
    const ir::IRDebugInfo* debug_info_ = nullptr; ///< Tuple/struct field names, captured at GenerateSingle entry
    std::map<std::string, std::string> tiling_headers_; ///< Tiling struct headers (filename -> content)

    CodeEmitter emitter_;                                 ///< Code emitter for structured output
    CodeContext context_;                                 ///< Context for variable tracking
    TypeConverter type_converter_;                        ///< Type converter
    const backend::Backend* backend_;                     ///< CCE backend instance (for op info, core type)
    std::string arch_ = "a3";                             ///< Target architecture ("a2", "a3", "a5")
    std::optional<ir::SectionKind> current_section_kind_; ///< Current section being generated (Cube/Vector/VF)
    std::unordered_map<std::string, std::string> tensor_to_pointer_; ///< Tensor var name ->raw pointer expression
    std::map<std::string, TensorDef> tensor_defs_;      ///< Prescan: cce var name ->TensorDef (for make_tensor views)
    std::map<std::string, std::string> tile_addresses_; ///< tile_name ->TASSIGN address expression

    // Loop tile hoisting: declarations collected during loop body visit, emitted before outermost loop
    int loop_depth_ = 0; ///< Current for-loop nesting depth (0 = not in loop)
    int if_depth_ = 0;   ///< Current if-stmt nesting depth (0 = not in if)
    std::map<std::string, std::string>
        vf_tile_ptrs_; ///< VF tile expr code ->hoisted vf_tile_ptr_N var (base + POST_UPDATE cursor)
    std::vector<std::string> loop_hoisted_decls_;    ///< Lines to hoist before outermost loop/if
    std::vector<std::string> section_hoisted_decls_; ///< VF section decls hoisted before __VEC_SCOPE__ (pre mem_bar)
    std::set<std::string> var_read_names_;           ///< Var names read anywhere in the function body
    std::unordered_map<std::string, int> var_read_counts_;   ///< Var name ->read count
    std::map<int, std::set<ir::PipeType>> cube_mutex_pipes_; ///< buf_id ->pipes in Cube section
    std::map<int, std::set<ir::PipeType>> vec_mutex_pipes_;  ///< buf_id ->pipes in Vec section

    /**
     * \brief Pre-scan the IR for mutex_id ->pipe mappings.
     *
     * Used on A5 to eliminate redundant PIPE_V get_buf/rls_buf: if a buf_id is
     * only used by PIPE_V (never by MTE2/MTE3/M/etc.), the V-side mutex
     * synchronization is unnecessary (V→V ops execute in order within the pipe).
     */
    void CollectMutexPipeInfo(const ir::StmtPtr& stmt);

    /**
     * \brief Pre-scan the IR for all Var names appearing in read positions
     * (Call args, Yield values, AssignStmt/ReturnStmt values, subscripts, etc.).
     *
     * Used to drop IfStmt phi return_vars that have no downstream consumer ->
     * the SSA pass conservatively
     * inserts phi nodes whenever a variable is re-assigned across control flow, but if the resulting phi var is never
     * read afterwards, EmitFullPhiIf would emit a dead declaration and
     * unused branch assignments.
     */
    void CollectVarReadNames(const ir::StmtPtr& stmt, std::set<std::string>& out) const;

    int tile_offset_counter_ = 0; ///< Counter for unique tile-offset GetItemExpr temp names
    int vf_tile_ptr_counter_ = 0; ///< Counter for unique VF base-ptr var names (vf_tile_ptr_N)

    // Tile type dedup: maps tile_type_str ->alias name already emitted
    std::map<std::string, std::string> emitted_tile_types_;

    /// Named-tuple struct: maps sanitized Var name (C++ symbol bound to a
    /// struct.create call) ->user-defined struct type name (e.g. "CubeCtx").
    /// Lets dynamic GetItem on a struct-tuple-array deduce the C++ element
    /// type without relying on decltype (codegen target is C-like, not real C++).
    std::map<std::string, std::string> struct_var_to_type_name_;

    /// Track emitted tile reference aliases to avoid C++ redefinition errors
    std::set<std::string> emitted_tile_aliases_;

    // Tuple Var C++ name -> the MakeTuple that was assigned to it.
    // Populated during body codegen by VisitStmt_(AssignStmtPtr) on tuple-typed lhs:
    // VisitExpr(rhs) drives current_tuple_ through MakeTuple literals, tuple-var aliases,
    // and chained static GetItem, all via the visitExpr chain. ForStmt iterArg/returnVar
    // are propagated in VisitStmt_(ForStmtPtr).
    std::map<std::string, ir::MakeTuplePtr> tuple_var_to_make_tuple_;

    int dyn_arr_counter_ = 0;

    /**
     * \brief Whether all element types of a tuple are structurally identical.
     *
     * Gate for emitting the dynamic-index array at the MakeTuple assignment: an array
     * is only valid when every element maps to the same C++ type. Empty tuple -> false.
     */
    bool IsHomogeneousTuple(const ir::TupleTypePtr& tt) const;

    /**
     * \brief Collect element C++ names from a tuple value expression.
     *
     * Body-codegen use. visitExpr-driven: VisitExpr(tuple_value) resolves the
     * underlying MakeTuple into current_tuple_, then each element is VisitExpr'd
     * to produce its C++ name in current_expr_value_. Dynamic-GetItem callers
     * guarantee all elements are tile/scalar Var or const literals, so each
     * element visit yields a non-empty current_expr_value_.
     * Returns empty vector on failure.
     */
    std::vector<std::string> CollectTupleElemNames(const ir::ExprPtr& tuple_value);
    std::string BuildDynamicTupleArrayDecl(const ir::TypePtr& elem_type, const std::vector<std::string>& elem_names,
                                           const std::string& arr_name, bool allow_struct_tuple) const;

    /// Emit-time valid-shape map: tile C++ name -> (row code, col code).
    /// Populated when set_validshape is emitted; consumed by the following load or store.
    std::map<std::string, std::pair<std::string, std::string>> tile_emit_shape_;
};

/**
 * \brief Inline all HELPER function calls into the kernel function.
 *
 * Walks the kernel body and replaces every Call whose op name matches
 * a HELPER function with the helper's body (variables renamed with
 * a unique per-call-site prefix, parameters substituted with call-site args,
 * ReturnStmt converted to assignment).  Returns a new Program containing
 * only the inlined kernel (if present) -- helpers are
 * removed.
 *
 * If the program has no helpers, returns it unchanged.
 */
ir::ProgramPtr InlineHelperCalls(const ir::ProgramPtr& program);

} // namespace codegen
} // namespace pypto

#endif // PYPTO_CODEGEN_CCE_CCE_CODEGEN_H_
