#!/usr/bin/env python3
# coding: utf-8
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------
"""Unit tests for the embedded compile-snippet generator (kernel extraction).

Layers:

* ``test_compile_snippet_assembles``, backend-free: valid Python, decorated functions kept under their
  original names, nested ``@pypto.frontend.jit`` kept, ``__pypto_compile`` exposed.
* the packing tests: which helper defs, constants and hoisted imports a snippet carries, across the
  factory, pinned/erased DIRECT, dotted-helper and PEP-563 forms.
* the golden suite: every case in ``GOLDEN_CASES`` is pinned whole-text against a checked-in file in
  ``test_compile_snippet_data/``, regenerated by that directory's ``render.py``.
* the fixed-point tests: a helper-free snippet is byte-identical across builds, and
  ``regen(regen(x)) == regen(x)`` once a hoisted import has become a header import.
* the emitted-decorator tests: the deployed ``@pypto.frontend.jit`` always reads
  ``run_mode": pypto.RunMode.SIM``, across every decorator spelling.
* ``test_compile_snippet_builds_real_kernel``: a real JIT build from the materialized snippet,
  asserting the ``.o`` and the ``*_aiv.json`` sidecar.
"""

import importlib
import importlib.util
import json
import os
from pathlib import Path
import sys
import tempfile

import pytest

import pypto
from pypto.extensions.torch_custom_op_litenpu.common import kernel_snippet

_EXPORT_TEST_DIR = Path(__file__).resolve().parent


def _load_samples_module(unique_name: str, filename: str):
    """Load a sibling ``*.py`` sample module by path (works without a parent package)."""
    path = _EXPORT_TEST_DIR / filename
    spec = importlib.util.spec_from_file_location(unique_name, path)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[unique_name] = mod
    spec.loader.exec_module(mod)
    return mod


samples = _load_samples_module("kernel_snippet_samples_ut", "kernel_snippet_samples.py")
pep563_direct = _load_samples_module("pep563_direct_snippet_ut", "multifile_fixtures/pep563_direct_kernel.py")
stdlib_forms = _load_samples_module("stdlib_forms_snippet_ut", "multifile_fixtures/stdlib_forms.py")

# soc with a bundled platform ini + bisheng support (KirinX90/dav-l300 is unsupported by
# the bundled compiler).
_SOC = "Kirin9030"


def _factory_snippet(create_kernel_func, kernel_body_func=None) -> str:
    return kernel_snippet.build_kernel_compile_snippet(
        create_kernel_func=create_kernel_func,
        infer_shape_func=samples.add_infer_shape,
        infer_dtype_func=samples.add_infer_dtype,
        n_inputs=2,
        kernel_body_func=kernel_body_func,
    )


def _snippet() -> str:
    return _factory_snippet(samples.create_add_kernel, samples.add_kernel_body)


def _direct_snippet(jit_kernel_func, declared_annotations=None) -> str:
    return kernel_snippet.build_kernel_compile_snippet(
        mode="jit_kernel",
        jit_kernel_func=jit_kernel_func,
        infer_shape_func=samples.add_infer_shape,
        infer_dtype_func=samples.add_infer_dtype,
        n_inputs=2,
        declared_annotations=declared_annotations,
    )


_PINNED_ANNOTATIONS = [
    {"shape": [1, 1, 8, 64], "dtype": "DT_FP16"},
    {"shape": [1, 1, 8, 64], "dtype": "DT_FP16"},
    {"shape": [1, 1, 8, 64], "dtype": "DT_FP16"},
]


# ---- the golden suite ---------------------------------------------------------------------------------

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "test_compile_snippet_data")
GOLDEN_SUFFIX = ".py.snippet"

# case name -> a zero-argument builder of that case's snippet text. The house golden convention stores
# input+golden PAIRS because its inputs are source files; the inputs here are Python objects from
# ``kernel_snippet_samples``, so the directory holds goldens only and this table carries the binding.
# The goldens deliberately do not end in ``.py``: they are generated, non-conforming source.
GOLDEN_CASES = {
    # ``factory_full`` and ``factory_discovered_helpers`` build from the same factory and differ only in
    # emitted helper ORDER: passing ``kernel_body_func`` places ``add_infer_tileshape`` before the body,
    # discovering it places the body first. Both also carry the captured ``_SAMPLE_TILE`` constant.
    "factory_full": lambda: _factory_snippet(samples.create_add_kernel, samples.add_kernel_body),
    "factory_body_omitted": lambda: _factory_snippet(samples.create_add_kernel_inlined),
    "factory_discovered_helpers": lambda: _factory_snippet(samples.create_add_kernel),
    "factory_cross_module_helper": lambda: _factory_snippet(samples.create_add_kernel_cross_module),
    "factory_stdlib_alias": lambda: _factory_snippet(stdlib_forms.create_kernel_stdlib_alias),
    "jit_pinned_annotations": lambda: _direct_snippet(
        samples.direct_add_kernel_pinned, declared_annotations=_PINNED_ANNOTATIONS
    ),
    "jit_erased_annotations": lambda: _direct_snippet(samples.direct_add_kernel_erased),
    "jit_dotted_helpers": lambda: _direct_snippet(samples.direct_dotted_helper_kernel),
}


# Parametrized from the case table rather than from the directory, so every declared case is always
# compared and a missing golden fails instead of shrinking the parameter set.
@pytest.mark.parametrize("case", sorted(GOLDEN_CASES))
def test_snippet_matches_golden(case):
    path = os.path.join(DATA_DIR, case + GOLDEN_SUFFIX)
    assert os.path.exists(path), f"{case}{GOLDEN_SUFFIX} is missing; run render.py"
    with open(path, encoding="utf-8") as fh:
        golden = fh.read()
    compile(golden, case + GOLDEN_SUFFIX, "exec")
    assert GOLDEN_CASES[case]() == golden, (
        f"{case}{GOLDEN_SUFFIX} is out of sync with the emitter; run render.py"
    )


def test_compile_snippet_assembles():
    """The factory snippet is valid Python exposing the deploy entry point; ``factory_full`` pins its
    whole text."""
    snippet = _snippet()
    compile(snippet, "<compile_snippet>", "exec")
    assert "def __pypto_compile(in_shapes, in_dtypes, attrs, soc_version):" in snippet


def test_compile_snippet_omits_optional_body():
    """kernel_body / infer_tileshape are optional (reference-style inlined kernel).

    Uses the genuinely inlined factory (``create_add_kernel_inlined``): it does not call a
    separate body, so omitting ``kernel_body_func`` yields a self-contained snippet.
    """
    snippet = kernel_snippet.build_kernel_compile_snippet(
        create_kernel_func=samples.create_add_kernel_inlined,
        infer_shape_func=samples.add_infer_shape,
        infer_dtype_func=samples.add_infer_dtype,
        n_inputs=2,
    )
    compile(snippet, "<compile_snippet>", "exec")
    assert "def add_kernel_body(" not in snippet


def test_compile_snippet_captures_referenced_module_constant():
    """A module-level constant the kernel closes over (``_SAMPLE_TILE``) is re-emitted as a
    literal in the snippet, so it resolves inside the embedded module (no NameError)."""
    snippet = kernel_snippet.build_kernel_compile_snippet(
        create_kernel_func=samples.create_add_kernel_inlined,
        infer_shape_func=samples.add_infer_shape,
        infer_dtype_func=samples.add_infer_dtype,
        n_inputs=2,
    )
    compile(snippet, "<compile_snippet>", "exec")
    assert "_SAMPLE_TILE = (1, 4, 1, 64)" in snippet


def test_compile_snippet_packs_referenced_helper_without_threading():
    """A referenced helper function is traced and packed, even when it is not explicitly threaded
    via ``kernel_body_func``.

    ``create_add_kernel`` calls ``add_kernel_body`` (which in turn calls ``add_infer_tileshape``).
    With ``kernel_body_func`` omitted, the recursive tracer discovers and emits both by source.
    """
    snippet = kernel_snippet.build_kernel_compile_snippet(
        create_kernel_func=samples.create_add_kernel,
        infer_shape_func=samples.add_infer_shape,
        infer_dtype_func=samples.add_infer_dtype,
        n_inputs=2,
    )
    compile(snippet, "<compile_snippet>", "exec")
    # Transitively referenced by add_kernel_body, and a same-module helper keeps its original name.
    assert "def add_infer_tileshape(" in snippet


def test_direct_pinned_snippet_emits_declared_annotations():
    """A pinned direct kernel's snippet carries ``declared_annotations=`` on ``CompileEntry(jit_kernel=...)``."""
    snippet = _direct_snippet(samples.direct_add_kernel_pinned, declared_annotations=_PINNED_ANNOTATIONS)
    compile(snippet, "<compile_snippet>", "exec")
    assert "declared_annotations=[{'shape': [1, 1, 8, 64], 'dtype': 'DT_FP16'}" in snippet


def test_direct_erased_snippet_omits_declared_annotations():
    """An erased direct kernel (no pinned literals) emits no ``declared_annotations=``, so it stays
    byte-identical."""
    snippet = _direct_snippet(samples.direct_add_kernel_erased)
    compile(snippet, "<compile_snippet>", "exec")
    assert "declared_annotations=" not in snippet


def test_direct_annotation_const_snippet_imports_without_nameerror(tmp_path):
    """A direct kernel that pins via named constants in its annotations (not literals) packs both the
    derived shape const (value snapshot) and the dtype const (``pypto.DT_FP16`` special emit), so the
    packed snippet has no unresolved name. Importing it triggers the jit parser over the pinned
    annotations, which must not raise NameError for ``_PIN_SHAPE`` / ``_PIN_DTYPE``.
    """
    snippet = _direct_snippet(samples.direct_add_kernel_pinned_const)
    assert "_PIN_SHAPE = (1, 8, 1, 64)" in snippet
    assert "_PIN_DTYPE = pypto.DT_FP16" in snippet
    mod_path = tmp_path / "annconst_kmod.py"
    mod_path.write_text(snippet)
    sys.path.insert(0, str(tmp_path))
    try:
        mod = importlib.import_module("annconst_kmod")
        # The pinned annotation names resolve in the module namespace (no NameError).
        assert getattr(mod, "_PIN_SHAPE") == (1, 8, 1, 64)
        assert getattr(mod, "_PIN_DTYPE").name == "DT_FP16"
        assert callable(getattr(mod, "__pypto_compile"))
    finally:
        sys.path.remove(str(tmp_path))
        sys.modules.pop("annconst_kmod", None)


def test_direct_erased_snippet_has_no_annotation_consts():
    """An erased direct kernel (no pinned annotation names) emits no annotation-const lines: the
    annotation-const channel only activates when the kernel pins named constants, so erased snippets
    are unaffected."""
    snippet = _direct_snippet(samples.direct_add_kernel_erased)
    compile(snippet, "<compile_snippet>", "exec")
    assert "= pypto.DT_" not in snippet


def test_direct_dotted_helper_snippet_packs_flattened_helpers(tmp_path):
    """A module-qualified-reference direct kernel (``pkg.mod.fn(...)``) packs its helpers under the
    flattened ``pkg__mod__fn`` def, rewrites the kernel body call sites to the flat name, and does not
    leak the helper package name. Materializing and importing it then resolves the flattened names at
    module scope with no NameError, and the kernel round-trips as a JitCallableWrapper."""
    snippet = _direct_snippet(samples.direct_dotted_helper_kernel)
    compile(snippet, "<compile_snippet>", "exec")
    # Self-contained: the helper package name survives only inside the flattened helper names.
    assert "sample_helper_pkg" not in snippet.replace("sample_helper_pkg__", "")
    mod_path = tmp_path / "dotted_helper_kmod.py"
    mod_path.write_text(snippet)
    sys.path.insert(0, str(tmp_path))
    try:
        mod = importlib.import_module("dotted_helper_kmod")
        # tile_helper is a plain function; add_into round-trips as a @function NestedFunctionMarker
        # (not a plain callable), so assert only that the flattened name resolves (no NameError).
        assert getattr(mod, "sample_helper_pkg__compute__tile_helper")() == (1, 4, 1, 64)
        assert getattr(mod, "sample_helper_pkg__compute__add_into") is not None
        assert callable(getattr(mod, "__pypto_compile"))
    finally:
        sys.path.remove(str(tmp_path))
        sys.modules.pop("dotted_helper_kmod", None)


def test_compile_snippet_builds_real_kernel(tmp_path):
    snippet = _snippet()
    mod_path = tmp_path / "embedded_kmod.py"
    mod_path.write_text(snippet)
    sys.path.insert(0, str(tmp_path))
    try:
        mod = importlib.import_module("embedded_kmod")
        compile_fn = getattr(mod, "__pypto_compile")
        # The deployed path passes dtype STRINGS (DataTypeToStr: ge::DT_FLOAT16 -> "float16"); a raw
        # enum int would raise "Unsupported dtype string '1'", an argument bug not a missing backend.
        fp16 = "float16"
        try:
            path = compile_fn([[8, 64], [8, 64]], [fp16, fp16], {}, _SOC)
        except (ImportError, OSError, pypto.error.PyptoError) as e:
            # Same narrow guard as test_from_jit_kernel's real build: only an absent or broken backend
            # skips. The snippet's CONTENT is asserted by the other tests in this module, and the
            # import above is outside the guard, so a malformed snippet still fails here.
            pytest.skip(f"DIRECT build unavailable on this host (backend): {type(e).__name__}: {str(e)[:160]}")

        # __pypto_compile returns the compiled .o path; the *_aiv.json launch sidecar (read
        # by C++ PrepareExecute) sits next to it with the full schema.
        assert path.endswith(".o") and os.path.exists(path), path
        sidecar = path[:-2] + ".json"
        assert os.path.exists(sidecar), sidecar
        with open(sidecar) as fh:
            meta = json.load(fh)
        for key in ("blockDim", "kernelBin", "kernelName", "workspaceSize", "argNames"):
            assert key in meta, f"sidecar missing {key!r}: {sorted(meta)}"
    finally:
        sys.path.remove(str(tmp_path))
        sys.modules.pop("embedded_kmod", None)


def test_compile_snippet_stdlib_alias_header_binds():
    """An aliased stdlib import inside a packed helper survives as a header statement that binds at
    deploy: the emitted header executes standalone and resolves the alias to the real module."""
    snippet = _factory_snippet(stdlib_forms.create_kernel_stdlib_alias)
    assert "import math as m" in snippet.splitlines()
    header = snippet.split("\n\n", 1)[0]
    ns: dict = {}
    exec(compile(header, "<snippet-header>", "exec"), ns)  # noqa: S102 - executing our own emitted header
    assert ns["m"].prod([2, 3]) == 6


# ---- function-local imports inside an entry block (kernel body / infer hook) -------------------------

def test_entry_body_local_import_direct_kernel():
    """A local import inside a direct kernel body round-trips through the entry span channel: the
    import is gone from the emitted kernel block and the target is packed and rewritten."""
    snippet = _direct_snippet(samples.direct_kernel_local_import)
    compile(snippet, "<snip>", "exec")
    assert "from import_hoist_bias import" not in snippet
    assert "BIAS = 41" in snippet
    assert "input0 + input1 + BIAS" in snippet
    assert "def direct_kernel_local_import(" in snippet


def test_entry_body_local_import_infer_hook():
    """A local import inside an infer hook body round-trips through the entry span channel too (the
    hook is an entry source, not a discovered helper)."""
    snippet = kernel_snippet.build_kernel_compile_snippet(
        mode="jit_kernel",
        jit_kernel_func=samples.direct_add_kernel_erased,
        infer_shape_func=samples.infer_shape_local_import,
        infer_dtype_func=samples.add_infer_dtype,
        n_inputs=2,
    )
    compile(snippet, "<snip>", "exec")
    assert "import math" in snippet.splitlines()[:6]  # header import math (stdlib build-time value)
    assert "\n    import math" not in snippet  # the function-local import line is gone
    assert "def infer_shape_local_import(" in snippet


def test_direct_kernel_pep563_roundtrips_count_n():
    """A direct top-level kernel file with ``from __future__ import annotations`` and 3 tensor params
    round-trips with the right tensor-param count, and the snippet contains no ``__future__``."""
    snippet = kernel_snippet.build_kernel_compile_snippet(
        mode="jit_kernel",
        jit_kernel_func=pep563_direct.pep563_direct_add_kernel,
        infer_shape_func=pep563_direct.pep563_infer_shape,
        infer_dtype_func=pep563_direct.pep563_infer_dtype,
        n_inputs=2,
    )
    assert "__future__" not in snippet
    tf = tempfile.NamedTemporaryFile("w", suffix=".py", delete=False)
    tf.write(snippet)
    tf.close()
    spec = importlib.util.spec_from_file_location("packed_pep563_" + str(abs(hash(snippet))), tf.name)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    kernel = getattr(mod, "pep563_direct_add_kernel")
    input_tensors, _non_tensor = kernel._get_signature()
    assert len(input_tensors) == 3


# ---- fixed points: a helper-free snippet, and regen(regen(x)) ---------------------------------------

def test_single_file_byte_identity_invariant():
    """A single-file direct kernel referencing only torch/pypto (no discovered helper) yields a
    byte-identical snippet across two builds: the span editor is a no-op with no rewrites."""
    assert _direct_snippet(samples.direct_add_kernel_erased) == _direct_snippet(samples.direct_add_kernel_erased)
    # And the kernel body is emitted verbatim (no canonical mangling of a helper-free kernel).
    snippet = _direct_snippet(samples.direct_add_kernel_erased)
    assert "def direct_add_kernel_erased(" in snippet
    assert "__direct_add_kernel_erased" not in snippet


def _reimport_and_rebuild(snippet, kernel_name, infer_shape_name, infer_dtype_name, tmp_path):
    modname = kernel_name + "_regen"
    (tmp_path / (modname + ".py")).write_text(snippet)
    sys.path.insert(0, str(tmp_path))
    try:
        mod = importlib.import_module(modname)
        return kernel_snippet.build_kernel_compile_snippet(
            mode="jit_kernel", jit_kernel_func=getattr(mod, kernel_name),
            infer_shape_func=getattr(mod, infer_shape_name),
            infer_dtype_func=getattr(mod, infer_dtype_name), n_inputs=2,
        )
    finally:
        sys.path.remove(str(tmp_path))
        sys.modules.pop(modname, None)


@pytest.mark.parametrize(("mod", "kernel", "infer_shape", "infer_dtype", "extra_token"), [
    (samples, "direct_kernel_local_import", "add_infer_shape", "add_infer_dtype", None),
    (pep563_direct, "pep563_direct_add_kernel", "pep563_infer_shape", "pep563_infer_dtype", None),
    (samples, "direct_add_kernel_erased", "infer_shape_local_import", "add_infer_dtype", "import math\n"),
])
def test_true_idempotence(mod, kernel, infer_shape, infer_dtype, extra_token, tmp_path):
    """regen(regen(x)) == regen(x) byte-identically: a hoisted import becomes a module-scope header
    import on re-trace, so the hoist-and-delete is a fixed point with no churn."""
    s1 = kernel_snippet.build_kernel_compile_snippet(
        mode="jit_kernel", jit_kernel_func=getattr(mod, kernel),
        infer_shape_func=getattr(mod, infer_shape),
        infer_dtype_func=getattr(mod, infer_dtype), n_inputs=2,
    )
    if extra_token is not None:
        assert extra_token in s1
    s2 = _reimport_and_rebuild(s1, kernel, infer_shape, infer_dtype, tmp_path)
    assert s1 == s2


def test_factory_byte_identity_invariant():
    """A factory snippet is byte-identical across two builds even when the pack rewrites cross-module
    helper references: the span editor and the canonical namer are both deterministic."""
    first = _factory_snippet(samples.create_add_kernel_cross_module)
    assert first == _factory_snippet(samples.create_add_kernel_cross_module)
    assert "def sample_helper_pkg__compute__tile_helper(" in first


def _reimport_and_rebuild_factory(snippet, factory_name, tmp_path):
    modname = factory_name + "_factory_regen"
    (tmp_path / (modname + ".py")).write_text(snippet)
    sys.path.insert(0, str(tmp_path))
    try:
        mod = importlib.import_module(modname)
        return kernel_snippet.build_kernel_compile_snippet(
            create_kernel_func=getattr(mod, factory_name),
            infer_shape_func=getattr(mod, "add_infer_shape"),
            infer_dtype_func=getattr(mod, "add_infer_dtype"),
            n_inputs=2,
        )
    finally:
        sys.path.remove(str(tmp_path))
        sys.modules.pop(modname, None)


@pytest.mark.parametrize(
    "factory_name",
    ["create_add_kernel", "create_add_kernel_inlined", "create_add_kernel_cross_module"],
)
def test_factory_true_idempotence(factory_name, tmp_path):
    """regen(regen(x)) == regen(x) byte-identically in factory mode: every packed helper and captured
    constant lands in the snippet's own module, so a re-trace of the materialized factory reproduces it."""
    s1 = _factory_snippet(getattr(samples, factory_name))
    s2 = _reimport_and_rebuild_factory(s1, factory_name, tmp_path)
    assert s1 == s2


# ---- the emitted decorator is always forced to SIM ---------------------------------------------------

def _decorator_line(snippet: str) -> str:
    """The ``@pypto.frontend.jit(...)`` line(s) of the emitted DIRECT kernel (up to its ``def``)."""
    lines = snippet.splitlines()
    start = next(i for i, ln in enumerate(lines) if "@pypto.frontend.jit" in ln)
    end = next(i for i, ln in enumerate(lines[start:], start) if ln.lstrip().startswith("def "))
    return "\n".join(lines[start:end])


def test_direct_snippet_forces_sim_decorator():
    # SOURCE kernel is decorated run_mode=NPU; the deploy snippet decorator must be forced to SIM.
    snippet = _direct_snippet(samples.direct_add_kernel_npu_source)
    deco = _decorator_line(snippet)
    assert "pypto.RunMode.SIM" in deco
    assert "RunMode.NPU" not in deco
    # A body line that references RunMode.NPU (not the decorator) must survive untouched.
    assert "_unused = pypto.RunMode.NPU" in snippet


# The decorator form matrix: forced or injected SIM, at the string level.

_BODY = "def add_kernel(a, b, c):\n    c.move(a + b)\n"


@pytest.mark.parametrize("deco", [
    '@pypto.frontend.jit(runtime_options={"run_mode": pypto.RunMode.NPU})\n',   # present NPU -> rewritten
    '@pypto.frontend.jit(runtime_options={"run_mode": pypto.RunMode.SIM})\n',   # present SIM -> unchanged
    '@pypto.frontend.jit\n',                                                    # bare, no parens -> injected
    '@pypto.frontend.jit()\n',                                                  # empty parens -> injected
    '@pypto.frontend.jit(codegen_options={"foo": 1})\n',                        # other kwargs -> injected
    '@pypto.frontend.jit(runtime_options={"foo": 1})\n',                        # runtime_options w/o run_mode
    '@pypto.frontend.jit(\n    codegen_options={"foo": 1},\n)\n',               # multi-line -> injected
    '@pypto.frontend.jit(codegen_options={"foo": 1})  # trailing comment\n',    # trailing comment -> injected
])
def test_force_sim_decorator_form_matrix(deco):
    out = kernel_snippet._force_sim_in_decorator(deco + _BODY)
    deco_span = out.split("def ", 1)[0]
    assert "pypto.RunMode.SIM" in deco_span
    assert "RunMode.NPU" not in deco_span
    # The kernel BODY must be preserved verbatim (only the decorator span is touched).
    assert out.endswith(_BODY)


def test_force_sim_decorator_non_literal_runtime_options_raises():
    # runtime_options=<NAME> (not an inline dict): can't inject a run_mode key safely -> clear error.
    block = '@pypto.frontend.jit(runtime_options=MY_OPTS)\n' + _BODY
    with pytest.raises(ValueError, match="runtime_options"):
        kernel_snippet._force_sim_in_decorator(block)
