# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

"""Cross-core access scanner for preload pipeline auto-sync.

Pure-AST analysis. Scans the kernel body for cross-core NBuffer declarations
(those configured with cross_core_forward_id / cross_core_backward_id), then
scans each @stage function body to determine, for each cross-core buffer it
touches, the access role (W/R) and the pipe of the op that does the access.

The result drives automatic wait/set_cross_core insertion at stage boundaries.
"""

from __future__ import annotations

import ast
from dataclasses import dataclass, field
from enum import Enum

from pypto.pypto_impl.ir import MemorySpace
from pypto_pro.language.parser._op_pipeline import (
    _BLOCK_OP_TILE_ROLES,
    get_move_pipe,
    get_op_pipe,
    get_store_pipe,
)

# MemorySpace attribute name (as written in pl.MemorySpace.<X>) -> enum value
_MEMORY_NAMES = {
    "Vec": MemorySpace.Vec,
    "Mat": MemorySpace.Mat,
    "Left": MemorySpace.Left,
    "Right": MemorySpace.Right,
    "Acc": MemorySpace.Acc,
}


def _extract_memory_from_make_tile_group(call: ast.Call) -> MemorySpace | None:
    """From a pl.make_tile_group(type=pl.TileType(..., target_memory=pl.MemorySpace.X), ...)
    call, extract the MemorySpace X. Returns None if not resolvable."""
    type_node = None
    for kw in call.keywords:
        if kw.arg == "type":
            type_node = kw.value
            break
    if not (isinstance(type_node, ast.Call)):
        return None
    for kw in type_node.keywords:
        if kw.arg == "target_memory":
            v = kw.value
            if isinstance(v, ast.Attribute) and v.attr in _MEMORY_NAMES:
                return _MEMORY_NAMES[v.attr]
    return None


def _is_make_tile_group(call: ast.Call) -> bool:
    """True if call is pl.make_tile_group(...) (or bare make_tile_group(...))."""
    return _get_ctor_name(call) == "make_tile_group"


@dataclass
class CrossCoreBuffer:
    """A cross-core NBuffer's configuration (from kernel-body declaration)."""

    name: str  # variable name, e.g. "qk_vec_db"
    memory: MemorySpace  # buffer memory space
    fwd_ids_node: ast.expr | None  # AST node for cross_core_forward_id value (e.g. a Name)
    bwd_ids_node: ast.expr | None  # AST node for cross_core_backward_id value
    fwd_slot_count: int  # len(forward id tuple) - for % N indexing
    bwd_slot_count: int  # len(backward id tuple)


class AccessRole(Enum):
    WRITE = "W"
    READ = "R"
    READ_WRITE = "RW"


@dataclass
class CrossCoreAccess:
    """One cross-core buffer access by a stage.

    A buffer may be accessed by multiple ops (same role) on different pipes.
    Sync at stage boundary needs:
      - first_pipe: pipe of the FIRST op  -> used by the *pre* (wait) sync
      - last_pipe:  pipe of the LAST op   -> used by the *post* (set) sync
    For a single-op access first_pipe == last_pipe.
    """

    buffer_name: str
    role: AccessRole
    first_pipe: str  # PipeType name of the first access op (for wait)
    last_pipe: str  # PipeType name of the last access op (for set)
    buffer: CrossCoreBuffer = None  # back-reference to the buffer config
    section_kind: str = ""  # for mix outer accesses: which sub-stage section
    # ("cube"/"vector") this access happens in, so the
    # outer sync can be wrapped in the right section.


@dataclass
class OverlapReverseSync:
    """Reverse sync descriptor for address-overlapping buffers in different stages.

    Generated by _build_overlap_reverse_syncs in the analyzer. The transformer
    inserts wait at the first_stage start and set at the last_stage end.
    """

    first_stage: str  # stage func_name where wait is inserted (earliest user)
    last_stage: str  # stage func_name where set is inserted (latest user)
    wait_pipe: str  # pipe for the wait (first op's pipe at first_stage)
    set_pipe: str  # pipe for the set (last op's pipe at last_stage)
    set_section_kind: str  # section_kind of last_stage (for pre-fire wrapping)
    slot_count: int  # number of event id slots (== buffer slot count)
    stage_gap: int = 0  # last_stage_idx - first_stage_idx (for pre-fire count)
    event_ids: list = field(default_factory=list)  # allocated event id values
    event_ids_var: str = ""  # lifted variable name for codegen (e.g. "_pl_overlap_ids_0")


@dataclass
class CrossCoreSyncContext:
    """Cross-core synchronization context — buffer declarations + access metadata.

    Groups all information needed by the transformer to generate cross-core sync
    (wait/set_cross_core), pre-fire, and lifted-id declarations. Populated by
    _scan_cross_core() during analysis.
    """

    # Buffer declarations: name -> CrossCoreBuffer (only cross-core buffers with fwd/bwd ids)
    buffers: dict = field(default_factory=dict)
    # All buffer memory spaces: name -> MemorySpace (includes local buffers, for pipe calc)
    all_memory: dict = field(default_factory=dict)
    # Inner buffer consumer info for mix pre-fire: {buffer_name: (section_kind, pipe)}
    inner_consumer_map: dict = field(default_factory=dict)
    # Lifted literal fwd_ids/bwd_ids: [(var_name, ast_literal)] to declare as variables
    lifted_ids: list = field(default_factory=list)
    # Per-buffer slot address ranges: name -> (memory, [(start, end), ...] per slot).
    # Covers ALL buffers (cross-core + local) for address-overlap detection.
    addr_ranges: dict = field(default_factory=dict)
    # Address-overlapping buffer pairs: [(buf_a, buf_b), ...] (same memory, ranges intersect)
    addr_overlaps: list = field(default_factory=list)
    # Scenario 2/3: reverse syncs needed for address-overlapping buffers in different stages.
    # Each entry: {first_stage, last_stage, wait_pipe, set_pipe, event_ids_node, slot_count}
    overlap_reverse_syncs: list = field(default_factory=list)


def _memory_name(mem: MemorySpace) -> str:
    """MemorySpace enum -> short pipe-table-compatible name. Not used directly;
    pipe is computed via the dynamic helpers or C++ backend metadata."""
    return str(mem)


def scan_all_buffer_memory(kernel_func_def: ast.FunctionDef) -> dict[str, MemorySpace]:
    """Return every make_tile_group declaration's memory by buffer variable name."""
    result: dict[str, MemorySpace] = {}
    for node in ast.walk(kernel_func_def):
        if not (isinstance(node, ast.Assign) and isinstance(node.value, ast.Call)):
            continue
        if not _is_make_tile_group(node.value):
            continue
        mem = _extract_memory_from_make_tile_group(node.value)
        if mem is None:
            continue
        for target in node.targets:
            if isinstance(target, ast.Name):
                result[target.id] = mem
    return result


def _eval_const(node: ast.expr, closure_vars: dict):
    """Evaluate a constant expression node using closure_vars as namespace.
    Returns the value, or None if it cannot be evaluated (e.g. references a
    runtime variable)."""
    try:
        code = compile(ast.Expression(body=node), "<addr>", "eval")
        return eval(code, {"__builtins__": {}}, dict(closure_vars))
    except Exception:
        return None


def _tile_type_slot_size(type_call: ast.Call, closure_vars: dict) -> int | None:
    """Compute per-slot byte size from a pl.TileType(shape=..., dtype=...) call.
    Returns None if shape/dtype cannot be resolved.

    slot_size = product(shape dims) * ceil(dtype_bits / 8)  (mirrors _buffer_parser).
    """
    shape_node = dtype_node = None
    for kw in type_call.keywords:
        if kw.arg == "shape":
            shape_node = kw.value
        elif kw.arg == "dtype":
            dtype_node = kw.value
    if shape_node is None or dtype_node is None:
        return None
    shape = _eval_const(shape_node, closure_vars)
    dtype = _eval_const(dtype_node, closure_vars)
    if not isinstance(shape, (list, tuple)) or dtype is None:
        return None
    elems = 1
    for d in shape:
        elems *= int(d)
    try:
        bits = int(dtype.get_bit())
    except Exception:
        return None
    return elems * ((bits + 7) // 8)


def scan_buffer_addr_ranges(kernel_func_def: ast.FunctionDef, closure_vars: dict) -> dict:
    """Scan every make_tile_group and compute each buffer's per-slot address ranges.

    Returns: name -> (memory, [(start, end), ...] per slot).
    Buffers whose addrs/shape/dtype cannot be statically resolved are skipped
    (they simply won't participate in overlap detection).

    addrs handling (mirrors _buffer_parser):
      - single value  -> contiguous slots: base + i*slot_size
      - list/tuple     -> one explicit start address per slot
    slot count = len(mutex_ids).
    """
    result: dict = {}
    for node in ast.walk(kernel_func_def):
        if not (isinstance(node, ast.Assign) and isinstance(node.value, ast.Call)):
            continue
        call = node.value
        if not _is_make_tile_group(call):
            continue
        memory = _extract_memory_from_make_tile_group(call)
        if memory is None:
            continue

        kwargs = {kw.arg: kw.value for kw in call.keywords if kw.arg}
        type_node = kwargs.get("type")
        addrs_node = kwargs.get("addrs")
        mutex_node = kwargs.get("mutex_ids")
        if not (isinstance(type_node, ast.Call) and addrs_node is not None and mutex_node is not None):
            continue

        slot_size = _tile_type_slot_size(type_node, closure_vars)
        mutex_ids = _eval_const(mutex_node, closure_vars)
        addrs = _eval_const(addrs_node, closure_vars)
        if slot_size is None or not isinstance(mutex_ids, (list, tuple)) or addrs is None:
            continue
        num = len(mutex_ids)

        if isinstance(addrs, (list, tuple)):
            if len(addrs) != num:
                continue  # malformed; skip (parser will raise the real error)
            starts = list(addrs)
        else:
            starts = [addrs + i * slot_size for i in range(num)]
        ranges = [(int(s), int(s) + slot_size) for s in starts]

        for target in node.targets:
            if isinstance(target, ast.Name):
                result[target.id] = (memory, ranges)
    return result


def detect_addr_overlaps(addr_ranges: dict, cross_core_names: set) -> list:
    """Detect address-overlapping buffer pairs relevant to cross-core sync.

    Two buffers overlap if they share the same MemorySpace and any of their slot
    ranges intersect. Only pairs where **at least one side is a cross-core buffer**
    are reported — overlaps between two local buffers (e.g. multiple views of the
    same UB region like p_f16_db / p_f16_main_db) are the user's / auto_mutex's
    concern, not the pipeline cross-core sync's. Returns (buf_a, buf_b) pairs
    (names sorted).

    Constraint: only pairwise overlap is supported. If any buffer overlaps with
    more than one other buffer (counting only cross-core-relevant overlaps),
    raises ValueError.
    """
    names = sorted(addr_ranges.keys())
    overlaps = []
    # buffer -> set of buffers it overlaps with (for the 3+ check)
    overlap_partners: dict = {}

    def _ranges_intersect(ra, rb) -> bool:
        for sa, ea in ra:
            for sb, eb in rb:
                if sa < eb and sb < ea:  # half-open interval intersection
                    return True
        return False

    for i, a in enumerate(names):
        for b in names[i + 1:]:
            # Skip if neither is a cross-core buffer (local-local overlap is not
            # a pipeline sync concern).
            if a not in cross_core_names and b not in cross_core_names:
                continue
            mem_a, ranges_a = addr_ranges[a]
            mem_b, ranges_b = addr_ranges[b]
            if mem_a != mem_b:
                continue
            if _ranges_intersect(ranges_a, ranges_b):
                # Slot count must be the same for overlapping buffers (precise
                # per-slot overlap tracking is not yet supported).
                if len(ranges_a) != len(ranges_b):
                    raise ValueError(
                        f"pipeline: address-overlapping buffers '{a}' and '{b}' have "
                        f"different slot counts ({len(ranges_a)} vs {len(ranges_b)}). "
                        f"Overlapping buffers must have the same number of slots."
                    )
                overlaps.append((a, b))
                overlap_partners.setdefault(a, set()).add(b)
                overlap_partners.setdefault(b, set()).add(a)

    for buf, partners in overlap_partners.items():
        if len(partners) > 1:
            raise ValueError(
                f"pipeline: buffer '{buf}' has overlapping addresses with multiple "
                f"buffers {sorted(partners)}. Only pairwise address overlap is "
                f"supported (at most 2 buffers may share a region)."
            )
    return overlaps


def scan_cross_core_buffers(
    kernel_func_def: ast.FunctionDef, closure_vars: dict
) -> tuple[dict[str, CrossCoreBuffer], list]:
    """Scan the kernel body for cross-core tile-group declarations.

    Returns:
        (dict mapping buffer variable name -> CrossCoreBuffer,
         lifted_ids: list of (var_name, ast_literal) for literal fwd/bwd ids
         that need to be declared as variables before the pipeline loop)
    """
    result: dict[str, CrossCoreBuffer] = {}
    lifted_ids: list[tuple[str, ast.expr]] = []

    for node in ast.walk(kernel_func_def):
        if not isinstance(node, ast.Assign):
            continue
        if not isinstance(node.value, ast.Call):
            continue
        call = node.value
        if not _is_make_tile_group(call):
            continue

        kwargs = {kw.arg: kw.value for kw in call.keywords if kw.arg}
        fwd_node = kwargs.get("fwd_ids")
        bwd_node = kwargs.get("bwd_ids")
        if fwd_node is None and bwd_node is None:
            continue

        names = [t.id for t in node.targets if isinstance(t, ast.Name)]
        bufname = names[0] if names else "<tile_group>"

        memory = _validate_buffer_memory(call, bufname)
        fwd_count, bwd_count = _validate_ids(fwd_node, bwd_node, bufname, closure_vars)
        fwd_node, bwd_node = _lift_literal_ids(fwd_node, bwd_node, bufname, lifted_ids)

        for target in node.targets:
            if isinstance(target, ast.Name):
                result[target.id] = CrossCoreBuffer(
                    name=target.id,
                    memory=memory,
                    fwd_ids_node=fwd_node,
                    bwd_ids_node=bwd_node,
                    fwd_slot_count=fwd_count,
                    bwd_slot_count=bwd_count,
                )

    return result, lifted_ids


def _validate_buffer_memory(call: ast.Call, bufname: str) -> MemorySpace:
    """L8: Validate and extract memory space from make_tile_group call."""
    memory = _extract_memory_from_make_tile_group(call)
    if memory is None:
        raise ValueError(
            f"pipeline: cross-core buffer '{bufname}' has no resolvable memory space. "
            f"Its make_tile_group(type=pl.TileType(..., target_memory=pl.MemorySpace.X)) "
            f"must set target_memory to a literal pl.MemorySpace.<X>."
        )
    return memory


def _validate_ids(fwd_node, bwd_node, bufname: str, closure_vars: dict) -> tuple[int, int]:
    """L11: Validate fwd_ids/bwd_ids are resolvable non-empty tuples."""
    fwd_count = _resolve_tuple_len(fwd_node, closure_vars)
    bwd_count = _resolve_tuple_len(bwd_node, closure_vars)
    if fwd_node is not None and fwd_count == 0:
        raise ValueError(
            f"pipeline: cross-core buffer '{bufname}' fwd_ids must be a non-empty tuple "
            f"(literal or a module-level tuple constant); could not resolve its length."
        )
    if bwd_node is not None and bwd_count == 0:
        raise ValueError(
            f"pipeline: cross-core buffer '{bufname}' bwd_ids must be a non-empty tuple "
            f"(literal or a module-level tuple constant); could not resolve its length."
        )
    return fwd_count, bwd_count


def _lift_literal_ids(fwd_node, bwd_node, bufname: str, lifted_ids: list) -> tuple[ast.expr, ast.expr]:
    """Lift literal fwd_ids/bwd_ids to variable names for codegen compatibility."""
    if fwd_node is not None and isinstance(fwd_node, (ast.Tuple, ast.List)):
        var_name = f"_pl_fwd_ids_{bufname}"
        lifted_ids.append((var_name, fwd_node))
        fwd_node = ast.Name(id=var_name, ctx=ast.Load())
    if bwd_node is not None and isinstance(bwd_node, (ast.Tuple, ast.List)):
        var_name = f"_pl_bwd_ids_{bufname}"
        lifted_ids.append((var_name, bwd_node))
        bwd_node = ast.Name(id=var_name, ctx=ast.Load())
    return fwd_node, bwd_node


def _get_slot_accessor_assignment(node: ast.AST, param_names: set[str]) -> tuple[str, str] | None:
    """Return slot variable and source buffer for ``slot = group.next()`` patterns."""
    if not isinstance(node, ast.Assign):
        return None
    if len(node.targets) != 1 or not isinstance(node.targets[0], ast.Name):
        return None
    if not isinstance(node.value, ast.Call):
        return None

    func = node.value.func
    if not isinstance(func, ast.Attribute) or func.attr not in ("next", "current", "previous"):
        return None
    if not isinstance(func.value, ast.Name) or func.value.id not in param_names:
        return None
    return node.targets[0].id, func.value.id


def scan_kernel_slot_to_buffer(func_def: ast.FunctionDef, cross_buffers: dict) -> dict[str, str]:
    """Scan the kernel body for `slot = buf.next()` (or .current()/.previous())
    where buf is a cross-core buffer, mapping slot variable -> buffer name.

    This handles the case where the user takes a slot OUTSIDE the stage function
    (in the pipeline loop) and passes the slot tile as a stage argument.
    """
    buf_names = set(cross_buffers.keys())
    slot_to_buffer: dict[str, str] = {}
    for node in ast.walk(func_def):
        acc = _get_slot_accessor_assignment(node, buf_names)
        if acc is not None:
            slot_name, buffer_name = acc
            slot_to_buffer[slot_name] = buffer_name
    return slot_to_buffer


def build_binding_map(
    func_def: ast.FunctionDef, call_args: list | None, caller_bindings: dict, kernel_slot_map: dict, cross_buffers: dict
) -> dict[str, tuple[str, bool]]:
    """Build the name -> (buffer, is_group) binding map for a stage function body.

    Resolves all names that reference a cross-core buffer (directly or indirectly)
    within this function scope. Handles:
      (a) Formal params bound via call-site positional args (three sources:
          the actual is a cross_buffer group / a kernel_slot / a name from
          caller_bindings).
      (b) .next()/.current()/.previous() calls in the body: slot = group.next().
      (c) Pure Name-to-Name alias assignments: tmp = some_known_name.

    Steps (b) and (c) iterate until stable (supports alias chains).

    Args:
        func_def: the stage function AST.
        call_args: list of AST args from the call site. If None, returns empty
            (no name-collision guessing).
        caller_bindings: binding map of the CALLING scope (for transparent pass-through).
        kernel_slot_map: kernel-body slot -> buffer map (from scan_kernel_slot_to_buffer).
        cross_buffers: declared cross-core buffers dict.

    Returns: {name: (buffer_declared_name, is_group)}
    """
    param_names = [a.arg for a in func_def.args.args if a.arg != "self"]
    result: dict[str, tuple[str, bool]] = {}

    # (a) Param bindings from call site (positional). Without call args we cannot
    # resolve bindings — name-collision guessing is intentionally NOT done.
    if call_args is None:
        return result
    for pos, arg in enumerate(call_args):
        if pos >= len(param_names) or not isinstance(arg, ast.Name):
            continue
        actual = arg.id
        if actual in cross_buffers:
            result[param_names[pos]] = (actual, True)
        elif actual in kernel_slot_map:
            result[param_names[pos]] = (kernel_slot_map[actual], False)
        elif actual in caller_bindings:
            result[param_names[pos]] = caller_bindings[actual]

    # (b) + (c) Propagate .next() and alias assignments until stable
    changed = True
    while changed:
        changed = False
        for node in ast.walk(func_def):
            if not isinstance(node, ast.Assign):
                continue
            if len(node.targets) != 1 or not isinstance(node.targets[0], ast.Name):
                continue
            target = node.targets[0].id
            if target in result:
                continue  # already resolved

            if isinstance(node.value, ast.Call):
                func = node.value.func
                is_slot_method = (
                    isinstance(func, ast.Attribute)
                    and func.attr in ("next", "current", "previous")
                    and isinstance(func.value, ast.Name)
                )
                if is_slot_method and func.value.id in result:
                    src_buf, src_is_group = result[func.value.id]
                    if src_is_group:
                        result[target] = (src_buf, False)
                        changed = True
                continue

            if isinstance(node.value, ast.Name) and node.value.id in result:
                result[target] = result[node.value.id]
                changed = True

    return result


def _build_slot_to_buffer_from_bindings(
    func_def: ast.FunctionDef, bindings: dict[str, tuple[str, bool]]
) -> dict[str, str]:
    """Build slot_to_buffer from binding map. Covers ALL params (for pipe resolution).

    - Names with is_group=False → directly map to their buffer (they are slots).
    - Names from `slot = param.next()` for ANY param → map to param's resolved name
      (for non-cross-core params, resolved name = param name itself for pipe calc).
    """
    slot_to_buffer: dict[str, str] = {}
    # All resolved slot names (is_group=False) → buffer
    for name, (buf, is_group) in bindings.items():
        if not is_group:
            slot_to_buffer[name] = buf
    # For pipe resolution: also scan .next() on non-cross-core params (local buffers).
    # Their resolved name is just the param name (standard pipe-table lookup).
    all_param_names = {a.arg for a in func_def.args.args if a.arg != "self"}
    for node in ast.walk(func_def):
        acc = _get_slot_accessor_assignment(node, all_param_names)
        if acc is not None:
            slot_name, param_name = acc
            if slot_name not in slot_to_buffer:
                # Resolve: if param is in bindings use its buffer, else param name itself
                if param_name in bindings:
                    slot_to_buffer[slot_name] = bindings[param_name][0]
                else:
                    slot_to_buffer[slot_name] = param_name
    return slot_to_buffer


def _scan_accesses_recursive(
    func_def: ast.FunctionDef,
    slot_to_buffer: dict[str, str],
    cross_buffers: dict[str, CrossCoreBuffer],
    all_buffer_memory: dict[str, MemorySpace],
    vf_func_defs: dict[str, ast.FunctionDef],
    cross_access: dict[str, tuple[str, str, str]],
    overlap_map: dict[str, str],
    local_access: dict[str, tuple[str, str]],
    bindings: dict,
    kernel_slot_map: dict,
    stage_func_defs: dict,
) -> None:
    """Scan op calls in SOURCE ORDER, descending into sub-stage (mix) calls.

    For each Call in DFS/source order:
      - sub-stage call → resolve sub bindings from THIS scope, recurse into sub body
      - pl.<op>(...)   → record cross-core / local access (leaf op)
      - VF helper call → record cross-core access

    stage_func_defs: {stage_name: FunctionDef} for all @stage functions, used to
    resolve and descend into sub-stage calls (any nesting depth).
    """
    for node in _iter_calls_in_order(func_def):
        if not isinstance(node, ast.Call):
            continue
        # Sub-stage call (mix): resolve sub bindings from this scope, recurse
        if isinstance(node.func, ast.Name) and node.func.id in stage_func_defs:
            sub_def = stage_func_defs[node.func.id]
            sub_bindings = build_binding_map(sub_def, node.args, bindings, kernel_slot_map, cross_buffers)
            sub_slot_to_buffer = _build_slot_to_buffer_from_bindings(sub_def, sub_bindings)
            _scan_accesses_recursive(
                sub_def,
                sub_slot_to_buffer,
                cross_buffers,
                all_buffer_memory,
                vf_func_defs,
                cross_access,
                overlap_map,
                local_access,
                sub_bindings,
                kernel_slot_map,
                stage_func_defs,
            )
            continue
        # pl.<op>(...) block op
        if (
            isinstance(node.func, ast.Attribute)
            and isinstance(node.func.value, ast.Name)
            and node.func.value.id == "pl"
        ):
            _handle_block_op(
                node, slot_to_buffer, cross_buffers, all_buffer_memory, cross_access, overlap_map, local_access
            )
        # VF helper call
        elif isinstance(node.func, ast.Name):
            _handle_vf_call(node, slot_to_buffer, cross_buffers, vf_func_defs, cross_access)


def _handle_block_op(
    node: ast.Call, slot_to_buffer, cross_buffers, all_buffer_memory, cross_access, overlap_map=None, local_access=None
):
    """Process a single pl.<op>(...) call for cross-core access."""
    overlap_map = overlap_map or {}
    if local_access is None:
        local_access = {}
    op_name = node.func.attr
    roles = _BLOCK_OP_TILE_ROLES.get(op_name)
    if roles is None:
        return
    if op_name == "fillpad":
        for kw in node.keywords:
            if kw.arg == "mode" and isinstance(kw.value, ast.Attribute) and kw.value.attr == "INPLACE":
                roles = _BLOCK_OP_TILE_ROLES["fillpad_inplace"]
                break
    pipe = None
    for argpos, arg in enumerate(node.args):
        buf = _tile_arg_buffer(arg, slot_to_buffer)
        if buf is None or argpos >= len(roles):
            continue
        role = roles[argpos]
        if role is None:
            continue
        if buf in cross_buffers:
            if pipe is None:
                pipe = _block_op_pipe(op_name, node, slot_to_buffer, all_buffer_memory)
            _record_access(cross_access, buf, role, pipe)
        elif buf in overlap_map:
            if pipe is None:
                pipe = _block_op_pipe(op_name, node, slot_to_buffer, all_buffer_memory)
            # Scenario 1: extend cross-core buffer's last_pipe
            cc_buf = overlap_map[buf]
            if cc_buf in cross_access:
                _extend_last_pipe(cross_access, cc_buf, pipe)
            # Record local buffer's pipe for scenario 2/3
            _record_local_access(local_access, buf, pipe)


def _handle_vf_call(node: ast.Call, slot_to_buffer, cross_buffers, vf_func_defs, access):
    """Process a single VF helper call for cross-core access."""
    vf_name = node.func.id
    vf_def = vf_func_defs.get(vf_name)
    if vf_def is None:
        return
    vf_roles = _scan_vf_roles(vf_def, vf_func_defs)
    vf_params = [a.arg for a in vf_def.args.args if a.arg != "self"]
    for argpos, arg in enumerate(node.args):
        buf = _tile_arg_buffer(arg, slot_to_buffer)
        if buf is None or buf not in cross_buffers or argpos >= len(vf_params):
            continue
        role = vf_roles.get(vf_params[argpos])
        if role is None:
            continue
        _record_access(access, buf, role, "V")


def _iter_calls_in_order(node: ast.AST):
    """Yield all ast.Call nodes in SOURCE order (DFS, child order)."""
    for child in ast.iter_child_nodes(node):
        if isinstance(child, ast.Call):
            yield child
        yield from _iter_calls_in_order(child)


def scan_stage_accesses(
    stage_func_def: ast.FunctionDef,
    cross_buffers: dict[str, CrossCoreBuffer],
    vf_func_defs: dict[str, ast.FunctionDef],
    all_buffer_memory: dict[str, MemorySpace],
    addr_overlaps: list | None = None,
    cross_access_out: list | None = None,
    local_access_out: dict | None = None,
    call_args: list | None = None,
    caller_bindings: dict | None = None,
    kernel_slot_map: dict | None = None,
    stage_func_defs: dict | None = None,
) -> None:
    """Scan a stage function body for cross-core buffer accesses (recursive).

    Supports arbitrary nesting: if the function body calls other @stage functions
    (mix/sub-stages), recursively resolves their param bindings and scans them.

    Args:
        stage_func_def: the @stage function AST
        cross_buffers: name -> CrossCoreBuffer (cross-core buffers)
        vf_func_defs: name -> FunctionDef for VF helper functions (for role scan)
        all_buffer_memory: name -> MemorySpace for ALL buffers (for move pipe)
        addr_overlaps: list of (buf_a, buf_b) address-overlapping pairs.
        cross_access_out: list to receive CrossCoreAccess results.
        local_access_out: dict to receive local overlapping buffer pipe info.
        call_args: list of AST args from the call site (None for fallback).
        caller_bindings: binding map of the calling scope (for param pass-through).
        kernel_slot_map: kernel-body slot -> buffer (from scan_kernel_slot_to_buffer).
        stage_func_defs: {stage_name: FunctionDef} for all @stage functions, used to
            resolve and descend into sub-stage calls (any nesting depth).
    """
    # Build binding map for this function scope
    bindings = build_binding_map(stage_func_def, call_args, caller_bindings or {}, kernel_slot_map or {}, cross_buffers)
    if not bindings:
        return

    # Group params for validation
    group_param_names = {p for p, (_b, ig) in bindings.items() if ig}
    _validate_slot_accessors(stage_func_def, group_param_names)

    # Build slot_to_buffer (covers all params for pipe resolution)
    slot_to_buffer = _build_slot_to_buffer_from_bindings(stage_func_def, bindings)

    # Scenario 1: overlap map
    stage_cc_buffers = {buf for (buf, _ig) in bindings.values()}
    overlap_map = _build_stage_overlap_map(addr_overlaps, cross_buffers, slot_to_buffer, stage_cc_buffers)

    # Accumulate accesses
    cross_access: dict[str, tuple[str, str, str]] = {}
    local_access: dict[str, tuple[str, str]] = {}

    # Recursive scan: process ops directly AND descend into sub-stage calls
    _scan_accesses_recursive(
        stage_func_def,
        slot_to_buffer,
        cross_buffers,
        all_buffer_memory,
        vf_func_defs,
        cross_access,
        overlap_map,
        local_access,
        bindings,
        kernel_slot_map or {},
        stage_func_defs or {},
    )

    # Export results
    if cross_access_out is not None:
        for buf_name, (role, first_pipe, last_pipe) in cross_access.items():
            cross_access_out.append(
                CrossCoreAccess(
                    buffer_name=buf_name,
                    role=AccessRole(role),
                    first_pipe=first_pipe,
                    last_pipe=last_pipe,
                    buffer=cross_buffers[buf_name],
                )
            )
    if local_access_out is not None:
        local_access_out.update(local_access)


def _build_stage_overlap_map(addr_overlaps, cross_buffers, slot_to_buffer, stage_cc_buffers) -> dict:
    """Build {local_buf -> cross_core_buf} for overlap pairs where BOTH buffers
    are accessed in THIS stage (i.e. the reuse happens within one stage — scenario 1).

    Only maps local (non-cross-core) buffer -> cross-core buffer. Pairs where both
    are cross-core, or that don't co-occur in this stage, are excluded here (those
    are scenarios 2/3, handled separately).

    Buffers accessed in this stage = cross-core buffers bound via the call site
    (stage_cc_buffers) plus every buffer that slot_to_buffer resolves to (which
    includes local buffers touched through their own slot accessors)."""
    result: dict[str, str] = {}
    if not addr_overlaps:
        return result
    # All buffer (declaration) names touched by this stage.
    touched = set(stage_cc_buffers) | set(slot_to_buffer.values())
    for a, b in addr_overlaps:
        if a not in touched or b not in touched:
            continue
        a_is_cc, b_is_cc = a in cross_buffers, b in cross_buffers
        # Scenario 1 = local + cross-core. (cross-core + cross-core is scenario 3.)
        if a_is_cc and not b_is_cc:
            result[b] = a
        elif b_is_cc and not a_is_cc:
            result[a] = b
    return result


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _validate_slot_accessors(stage_func_def: ast.FunctionDef, group_param_names: set[str]) -> None:
    """L10: cross-core buffer slot accessors must be `slot = param.next()` form.

    group_param_names: formal params that carry a cross-core buffer GROUP (the ones
    the body calls .next()/.current()/.previous() on)."""
    accessor_rhs_ids = set()
    for node in ast.walk(stage_func_def):
        sa = _get_slot_accessor_assignment(node, group_param_names)
        if sa is not None:
            accessor_rhs_ids.add(id(node.value))
    for node in ast.walk(stage_func_def):
        if not (isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)):
            continue
        if node.func.attr not in ("next", "current", "previous"):
            continue
        if not (isinstance(node.func.value, ast.Name) and node.func.value.id in group_param_names):
            continue
        if id(node) in accessor_rhs_ids:
            continue
        raise ValueError(
            f"pipeline: cross-core buffer group '{node.func.value.id}' slot accessor "
            f"`.{node.func.attr}()` must be assigned to a simple variable "
            f"(`slot = {node.func.value.id}.{node.func.attr}()`); inline/chained/"
            f"tuple-unpack forms are not supported."
        )


def _get_ctor_name(call: ast.Call) -> str | None:
    """Get the constructor name from a call like pl.UBNBuffer(...) -> 'UBNBuffer'."""
    if isinstance(call.func, ast.Attribute):
        return call.func.attr
    if isinstance(call.func, ast.Name):
        return call.func.id
    return None


def _resolve_tuple_len(node: ast.expr | None, closure_vars: dict) -> int:
    """Resolve the length of a tuple-valued node (Name referencing a module-level
    tuple, or a literal Tuple)."""
    if node is None:
        return 0
    if isinstance(node, (ast.Tuple, ast.List)):
        return len(node.elts)
    if isinstance(node, ast.Name):
        val = closure_vars.get(node.id)
        if isinstance(val, (tuple, list)):
            return len(val)
    return 0


def _tile_arg_buffer(arg: ast.expr, slot_to_buffer: dict[str, str]) -> str | None:
    """If arg is a bare slot variable (from group.next()) that maps to a buffer,
    return the buffer name; else None.

    New API: group.next() returns a bare tile, so op args are plain Names
    (e.g. pl.move(qk_left, cur_k)), not `slot.tile` attributes.
    """
    if isinstance(arg, ast.Name):
        return slot_to_buffer.get(arg.id)
    return None


def _block_op_pipe(
    op_name: str, call: ast.Call, slot_to_buffer: dict[str, str], all_buffer_memory: dict[str, MemorySpace]
) -> str:
    """Determine the pipe name for a block op accessing a cross-core buffer."""
    if op_name == "move":
        # move(dst, src): pipe depends on src/dst memory
        dst_mem = _arg_memory(call.args[0] if call.args else None, slot_to_buffer, all_buffer_memory)
        src_mem = _arg_memory(call.args[1] if len(call.args) > 1 else None, slot_to_buffer, all_buffer_memory)
        if src_mem is not None and dst_mem is not None:
            return _pipe_name(get_move_pipe(src_mem, dst_mem))
        return "V"
    if op_name in ("store", "store_tile"):
        src_mem = _arg_memory(call.args[1] if len(call.args) > 1 else None, slot_to_buffer, all_buffer_memory)
        if src_mem is not None:
            return _pipe_name(get_store_pipe(src_mem))
        return "V"
    pipe = get_op_pipe(op_name)
    return _pipe_name(pipe) if pipe is not None else "V"


def _arg_memory(arg, slot_to_buffer, all_buffer_memory) -> MemorySpace | None:
    """Get the MemorySpace of a `slot.tile` arg (any buffer, cross-core or local)."""
    buf = _tile_arg_buffer(arg, slot_to_buffer) if arg is not None else None
    if buf is not None:
        return all_buffer_memory.get(buf)
    return None


def _pipe_name(pipe) -> str:
    """PipeType enum -> short name string used in generated pl.PipeType.<NAME>."""
    # pipe is a PipeType enum; its name attribute gives FIX/V/MTE1/...
    return getattr(pipe, "name", str(pipe).split(".")[-1])


def _record_access(access: dict, buf: str, role: str, pipe: str) -> None:
    """Record a buffer access (called in SOURCE order). Tracks both the first
    op's pipe and the last op's pipe for the buffer.

    Contract: within one stage a buffer has a single role (all W for a producer,
    all R for a consumer — never both). The sync at the stage boundary uses:
      - pre (wait, before stage): the FIRST op's pipe
      - post (set, after stage):  the LAST op's pipe

    Stored as access[buf] = (role, first_pipe, last_pipe). First op sets both;
    subsequent ops (source order) only update last_pipe.
    """
    existing = access.get(buf)
    if existing is None:
        access[buf] = (role, pipe, pipe)  # first==last on first op
        return
    ex_role, first_pipe, _ = existing
    # L9: a stage must be EITHER producer (all W) OR consumer (all R) of a given
    # cross-core buffer, never both.
    if ex_role != role:
        raise ValueError(
            f"pipeline: cross-core buffer '{buf}' is both read and written within a "
            f"single stage (roles {ex_role} and {role}). A stage must be either the "
            f"producer (write-only) or the consumer (read-only) of a cross-core buffer."
        )
    access[buf] = (ex_role, first_pipe, pipe)  # keep first, update last


def _extend_last_pipe(access: dict, buf: str, pipe: str) -> None:
    """Extend a cross-core buffer's last_pipe to a later pipe (scenario 1).

    Called when a local buffer sharing the same physical address is accessed AFTER
    the cross-core buffer's last op. Only updates last_pipe — does not touch role
    or first_pipe. If the buffer has no entry yet in access (cross-core buffer not
    accessed in this stage), this is a no-op.
    """
    existing = access.get(buf)
    if existing is None:
        return
    ex_role, first_pipe, _ = existing
    access[buf] = (ex_role, first_pipe, pipe)


def _record_local_access(local_access: dict, buf: str, pipe: str) -> None:
    """Record a local (non-cross-core) overlapping buffer's pipe: (first_pipe, last_pipe).

    Called in SOURCE order. First op sets both; subsequent ops update last_pipe.
    Unlike _record_access, there is NO role/L9 check — a local buffer may be both
    read and written within a stage (scenario 2/3 only needs its first/last pipe)."""
    existing = local_access.get(buf)
    if existing is None:
        local_access[buf] = (pipe, pipe)  # first == last on first op
    else:
        first_pipe, _ = existing
        local_access[buf] = (first_pipe, pipe)  # keep first, update last


def _root_name(node):
    """Return the root name of a possibly indexed/attributed expression."""
    cur = node
    while True:
        if isinstance(cur, ast.Name):
            return cur.id
        if isinstance(cur, ast.BinOp):
            cur = cur.left
            continue
        if isinstance(cur, (ast.Attribute, ast.Subscript)):
            cur = cur.value
            continue
        return None


def _merge_vf_role(result: dict[str, str], name: str, role: str | None) -> None:
    """Merge one VF read/write role into the per-param role map."""
    ex = result.get(name)
    if ex is None:
        result[name] = role
    elif ex != role and role is not None:
        result[name] = "RW"


def _record_vf_call_role(sub: ast.Call, param_names: set[str], result: dict[str, str]) -> None:
    """Record the R/W role represented by a single vf load/store call.

    Handles both statement form (vf.load_align(dst_reg, ptr, ...)) and
    assignment form (ptr_arg = vf.load_align(ptr, ...)).
    """
    if not isinstance(sub.func, ast.Attribute):
        return
    # Only vf.* calls are relevant (guards against pl.load etc. in non-VF helpers)
    if not (isinstance(sub.func.value, ast.Name) and sub.func.value.id == "vf"):
        return
    op = sub.func.attr
    if op.startswith("load") and len(sub.args) >= 1:
        root = None
        if len(sub.args) >= 3:
            root = _root_name(sub.args[1])
            if root not in param_names:
                root = None
        if root is None:
            root = _root_name(sub.args[0])
        if root in param_names:
            _merge_vf_role(result, root, "R")
    elif op.startswith("store") and len(sub.args) >= 1:
        root = _root_name(sub.args[0])
        if root in param_names:
            _merge_vf_role(result, root, "W")


def _scan_vf_roles(vf_func_def: ast.FunctionDef, vf_func_defs: dict | None = None) -> dict[str, str]:
    """Scan a VF helper body for param R/W roles.

    Works for both ``@pl.vector_function`` decorated functions (scans
    ``vf.load_*`` / ``vf.store_*`` calls directly) and plain wrapper functions
    that delegate to a known VF function (propagates roles through the call's
    positional argument mapping, recursively for multi-level chains).

    - vf.load_*(reg, ptr, ...) -> ptr param is "R"
    - vf.store_*(ptr, reg, ...) -> ptr param is "W"
    - both -> "RW"
    """
    param_names = {a.arg for a in vf_func_def.args.args if a.arg != "self"}
    result: dict[str, str] = {}

    for sub in ast.walk(vf_func_def):
        if isinstance(sub, ast.Call):
            _record_vf_call_role(sub, param_names, result)
            # Propagate roles through calls to known VF functions (recursive)
            if vf_func_defs and isinstance(sub.func, ast.Name):
                callee_def = vf_func_defs.get(sub.func.id)
                if callee_def is not None and callee_def is not vf_func_def:
                    callee_roles = _scan_vf_roles(callee_def, vf_func_defs)
                    callee_params = [a.arg for a in callee_def.args.args if a.arg != "self"]
                    for argpos, arg in enumerate(sub.args):
                        if argpos >= len(callee_params):
                            break
                        callee_param = callee_params[argpos]
                        role = callee_roles.get(callee_param)
                        if role is None:
                            continue
                        root = _root_name(arg)
                        if root in param_names:
                            _merge_vf_role(result, root, role)
    return result
