#!/usr/bin/env python3
# coding: utf-8
# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------
import enum
from typing import Iterator, overload, Union, List, Dict, Tuple, Optional, NoReturn

from . import ir


class InternalError(Exception):
    """Exception raised when an internal system error occurs"""


class LogLevel(enum.IntEnum):
    DEBUG = ...
    INFO = ...
    WARN = ...
    ERROR = ...
    FATAL = ...
    EVENT = ...


def set_log_level(level: LogLevel) -> None:
    """Set the log level threshold."""
    ...


def get_log_level() -> LogLevel:
    """Get the current log level threshold."""
    ...


def log(level: LogLevel, message: str) -> None:
    """Log a message at the specified level."""
    ...


def check(condition: bool, message: str) -> None:
    """Check a condition and throw ValueError if it fails."""
    ...


def internal_check(condition: bool, message: str) -> None:
    """Check a condition and throw InternalError if it fails."""
    ...


def raise_error(error_type: str, message: str) -> NoReturn:
    """Raise an error from C++ for testing error handling."""


class DataType(enum.Enum):
    DT_INT4 = ...
    DT_INT8 = ...
    DT_INT16 = ...
    DT_INT32 = ...
    DT_INT64 = ...
    DT_FP8 = ...
    DT_FP16 = ...
    DT_FP32 = ...
    DT_BF16 = ...
    DT_HF4 = ...
    DT_HF8 = ...
    DT_FP8E4M3 = ...
    DT_FP8E5M2 = ...
    DT_FP8E8M0 = ...
    DT_FP4_E2M1 = ...
    DT_FP4_E2M1X2 = ...
    DT_FP4_E1M2 = ...
    DT_FP4_E1M2X2 = ...
    DT_UINT8 = ...
    DT_UINT16 = ...
    DT_UINT32 = ...
    DT_UINT64 = ...
    DT_BOOL = ...
    DT_DOUBLE = ...
    DT_BOTTOM = ...


class ScatterMode(enum.Enum):
    NONE = ...      # 仅做数据搬运
    ADD = ...       # 加法模式
    MULTIPLY = ...  # 乘法模式


class NodeType(enum.Enum):
    LOCAL = ...
    INCAST = ...
    OUTCAST = ...


class TileOpFormat(enum.Enum):
    TILEOP_ND = ...
    TILEOP_NZ = ...


class CachePolicy(enum.Enum):
    NONE_CACHEABLE = ...


class ReduceMode(enum.Enum):
    ATOMIC_ADD = ...


class FunctionType(enum.Enum):
    STATIC = ...
    DYNAMIC = ...
    DYNAMIC_LOOP = ...


class GraphType:
    TENSOR_GRAPH = ...


class CastMode(enum.Enum):
    CAST_NONE = ...
    CAST_RINT = ...
    CAST_ROUND = ...
    CAST_FLOOR = ...
    CAST_CEIL = ...
    CAST_TRUNC = ...
    CAST_ODD = ...

class SaturationMode(enum.Enum):
    OFF = ...
    ON = ...

class DequantScaleRoundingMode(enum.Enum):
    ROUND_UP = ...
    ROUND_DOWN = ...

class PrecisionType(enum.Enum):
    INTRINSIC = ...
    HIGH_PRECISION = ...

class LogBaseType(enum.Enum):
    LOG_E = ...
    LOG_2 = ...
    LOG_10 = ...


class OpType(enum.Enum):
    EQ = ...
    NE = ...
    LT = ...
    LE = ...
    GT = ...
    GE = ...


class OutType(enum.Enum):
    BOOL = ...
    BIT = ...


class TopKAlgo(enum.Enum):
    MERGE_SORT = ...
    RADIX_SELECT = ...


class ReLuType(enum.Enum):
    NO_RELU = ...
    RELU = ...


class TransMode(enum.Enum):
    CAST_NONE = ...
    CAST_RINT = ...
    CAST_ROUND = ...


class AtomicRMWMode(enum.Enum):
    ADD = ...
    MIN = ...
    MAX = ...


class Element:

    def __init__(self, dtype: DataType, data: Union[int, float]): ...

    def _get_signed_data(self) -> int: ...

    def _get_float_data(self) -> float: ...

    def _get_data_type(self) -> DataType: ...

    def _is_float(self) -> bool: ...


class SymbolicScalar:

    @overload
    def __init__(self): ...

    @overload
    def __init__(self, name: str): ...

    @overload
    def __init__(self, value: int): ...

    @overload
    def __init__(self, name: str, value: int): ...

    @overload
    def __init__(self, expr: ir.Expr): ...

    def __eq__(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...

    def __ne__(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...

    def __lt__(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...

    def __le__(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...

    def __gt__(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...

    def __ge__(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...

    def __add__(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...

    def __radd__(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...

    def __sub__(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...

    def __rsub__(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...

    def __mul__(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...

    def __rmul__(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...

    def __truediv__(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...

    def __rtruediv__(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...

    def __mod__(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...

    def __rmod__(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...

    def __rfloordiv__(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...

    def __floordiv__(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...

    def __pos__(self) -> SymbolicScalar: ...

    def __neg__(self) -> SymbolicScalar: ...

    def __invert__(self) -> SymbolicScalar: ...

    def __bool__(self) -> bool: ...

    def __int__(self) -> int: ...

    def is_concrete(self) -> bool: ...

    def concrete(self) -> int: ...

    def is_symbol(self) -> bool: ...

    def is_expression(self) -> bool: ...

    def is_immediate(self) -> bool: ...

    def simplify(self) -> SymbolicScalar: ...

    def min(self) -> SymbolicScalar: ...

    def max(self) -> SymbolicScalar: ...

    def as_variable(self) -> None: ...

    def as_expr(self) -> ir.Expr: ...

    def as_var(self) -> ir.Var: ...

    @staticmethod
    def tenary(cond: SymbolicScalar, true_val: SymbolicScalar, false_val: SymbolicScalar) -> SymbolicScalar: ...


class LogicalTensor(ir.Var):
    """Logical tensor"""


class Tensor:

    @overload
    def __init__(self): ...

    @overload
    def __init__(self, dtype: DataType, shape: List[int],
                 name: str = "", format: TileOpFormat = TileOpFormat.TILEOP_ND): ...

    @overload
    def __init__(self, dtype: DataType, shape: List[SymbolicScalar],
                 name: str = "", format: TileOpFormat = TileOpFormat.TILEOP_ND): ...

    @overload
    def __init__(self, logical_tensor: LogicalTensor): ...

    def GetDataType(self) -> DataType: ...

    def GetShape(self) -> List[int]: ...

    def GetValidShape(self) -> List[SymbolicScalar]: ...

    def Move(self, other: Tensor) -> Tensor: ...

    def SetCachePolicy(self, policy: CachePolicy, value: bool): ...

    def GetCachePolicy(self, policy: CachePolicy) -> bool: ...

    def SetName(self, name: str): ...

    def GetName(self) -> str: ...

    def Id(self) -> int: ...

    def Dim(self) -> int: ...

    def Format(self) -> TileOpFormat: ...

    def LogicalTensor(self) -> LogicalTensor: ...

    def IsEmpty(self) -> bool: ...


def GetInputShape(a: Tensor, axis: int) -> SymbolicScalar: ...


def GetTensorData(
        a: Tensor, offset: List[SymbolicScalar]) -> SymbolicScalar: ...


def SetTensorData(value: SymbolicScalar,
                  offset: List[SymbolicScalar], dst: Tensor): ...


def SetSpan(fname: str, lineno: int) -> None: ...


def ClearSpan() -> None: ...


class DeviceTensorData:

    def __init__(self, dtype: DataType, addr: int, shape: List[int]): ...

    def GetDataType(self) -> DataType: ...

    def GetDataPtr(self) -> int: ...

    def GetShape(self) -> List[int]: ...

    def Format(self) -> TileOpFormat: ...


class RecordIfBranch:

    def __init__(self, cond: SymbolicScalar,
                 file: str = "", line: int = 0): ...

    def __bool__(self) -> bool: ...


class LoopRange:

    def __init__(self, start: SymbolicScalar, stop: SymbolicScalar,
                 step: Union[SymbolicScalar, int]): ...

    def Dump(self) -> str: ...

    def Begin(self) -> SymbolicScalar: ...

    def End(self) -> SymbolicScalar: ...

    def Step(self) -> SymbolicScalar: ...


def IsLoopBegin(symbol: SymbolicScalar, begin: SymbolicScalar) -> SymbolicScalar: ...


def IsLoopEnd(symbol: SymbolicScalar, end: SymbolicScalar) -> SymbolicScalar: ...


class RecordFunc:

    @overload
    def __init__(self, name: str): ...

    @overload
    def __init__(self, name: str, args: List[Tensor]): ...

    @overload
    def __init__(self, name: str, inputs: List[Tensor] = [], outputs: List[Tensor] = [],
                 inplaces: List[tuple[Tensor, Tensor]] = []): ...

    def EndFunction(self): ...


class RecordLoopFunc:

    def __init__(self, name: str, func_type: FunctionType, iter_name: str, loop_range: LoopRange,
                 unroll_List: set[int] = set(), submit_before_loop: bool = False): ...

    def __iter__(self) -> Iterator[SymbolicScalar]: ...


def BeginFunction(name: str, graph_type: GraphType,
                  func_type: FunctionType, *args): ...


def EndFunction(name: str, generate_call: bool = True): ...


def GetWorkSpaceSize(handle: int, inputs: List[DeviceTensorData], outputs: List[DeviceTensorData]) -> int: ...


def SetVecTile(*shapes: int): ...


def GetVecTile() -> List[int]: ...


def SetCubeTile(m: List[int], k: List[int],
                n: List[int], enable_split_k: bool = False): ...


def GetCubeTile() -> Tuple[List[int], List[int], List[int], bool]: ...


def SetConvTile(tileL1Info: TileL1Info, tileL0Info: TileL0Info, setL0Tile: bool = False): ...


def GetConvTile() -> Tuple[TileL1Info, TileL0Info, bool]: ...


def SetMatrixSize(size: List[int]): ...


def SetBuildStatic(static: bool): ...


def SetSemanticLabel(label: str, filename: str, lineno: int): ...


@overload
def SetOption(key: str, value: bool): ...


@overload
def SetOption(key: str, value: str): ...


@overload
def SetOption(key: str, value: int): ...


@overload
def SetOption(key: str, value: List[int]): ...


@overload
def SetOption(key: str, value: Dict[int, int]): ...


def GetOptions() -> Dict[str, Union[bool, str, int, List[int], Dict[int, int]]]: ...


def SetPrintOptions(edge_items: int, precision: int, threshold: int, linewidth: int): ...


def BytesOf(t: DataType) -> int: ...


def ResetOptions(): ...


def Reset(): ...


def Dump() -> str: ...

# utils
def OutputErrorMessage(): ...

# runtime
def DeviceInit(): ...


def DeviceFini(): ...



def CopyToHost(devTensor: DeviceTensorData, hostTensor: DeviceTensorData): ...


def CopyToDev(devTensor: DeviceTensorData, hostTensor: DeviceTensorData): ...


def SetVerifyData(inputs: List[DeviceTensorData],
                  outputs: List[DeviceTensorData],
                  goldens: List[DeviceTensorData]): ...


def OperatorDeviceRunOnceDataFromDevice(operator_id: int,
                                        a: List[DeviceTensorData],
                                        dst: List[DeviceTensorData],
                                        stream_id: int,
                                        workspace_ptr: int,
                                        ctrl_cache: int): ...


def DeviceRunOnceDataFromHost(a: List[DeviceTensorData],
                              dst: List[DeviceTensorData]): ...


def OperatorBegin() -> int: ...


def OperatorEnd(operator_id: int): ...


def OperatorDeviceSynchronize(stream_id: int): ...


def CostModelRunOnceDataFromHost(a: List[DeviceTensorData],
                              dst: List[DeviceTensorData]): ...

# operations


def Add(a: Tensor, b: Union[Tensor, Element]) -> Tensor: ...


def Sub(a: Tensor, b: Union[Tensor, Element]) -> Tensor: ...


def Mul(a: Tensor, b: Union[Tensor, Element]) -> Tensor: ...


def Div(a: Tensor, b: Union[Tensor, Element], precision_type: PrecisionType = PrecisionType.HIGH_PRECISION) -> Tensor: ...

def Remainder(a: Union[Tensor, Element], b: Union[Tensor, Element], precision_type: PrecisionType = PrecisionType.HIGH_PRECISION) -> Tensor: ...


def Pow(a: Tensor, b: Union[Tensor, Element], precision_type: PrecisionType = PrecisionType.HIGH_PRECISION) -> Tensor: ...


@overload
def View(a: Tensor, shapes: List[int],
         offsets: List[Union[int, SymbolicScalar]]) -> Tensor: ...


@overload
def View(a: Tensor, shapes: List[int], valid_shape: Optional[List[Union[int, SymbolicScalar]]],
         offsets: List[Union[int, SymbolicScalar]]) -> Tensor: ...


@overload
def View(a: Tensor, dtype: DataType) -> Tensor: ...

def Exp(a: Tensor, precision_type: PrecisionType = PrecisionType.INTRINSIC) -> Tensor: ...


def Exp2(a: Tensor) -> Tensor: ...


def Expm1(a: Tensor) -> Tensor: ...


def Permute(a: Tensor, perm: List[int]) -> Tensor: ...


def Transpose(a: Tensor, axis: List[int]) -> Tensor: ...


def Abs(a: Tensor) -> Tensor: ...


def Reciprocal(a: Tensor, precision_type: PrecisionType = PrecisionType.INTRINSIC) -> Tensor: ...


def Round(a: Tensor, decimals: int = 0) -> Tensor: ...


def Rsqrt(a: Tensor, precision_type: PrecisionType = PrecisionType.INTRINSIC) -> Tensor: ...


def Sqrt(a: Tensor, precision_type: PrecisionType = PrecisionType.INTRINSIC) -> Tensor: ...


def Ceil(a: Tensor) -> Tensor: ...


def Floor(a: Tensor) -> Tensor: ...


def Trunc(a: Tensor) -> Tensor: ...


def Neg(a: Tensor) -> Tensor: ...


def Erfc(a: Tensor) -> Tensor: ...


def Log(a: Tensor, base: LogBaseType, precision_type: PrecisionType = PrecisionType.INTRINSIC) -> Tensor: ...

def Tan(a: Tensor) -> Tensor: ...

def Cast(a: Tensor, dtype: DataType, mode: CastMode, satmode: SaturationMode = SaturationMode.OFF) -> Tensor: ...

def index_select(src: Tensor,  dim: int,  indices: Tensor) -> Tensor: ...

@overload
def Scatter(self: Tensor, indices: Tensor, src: Element, axis: int,
            reduce: ScatterMode = ScatterMode.NONE) -> Tensor: ...
@overload
def Scatter(self: Tensor, indices: Tensor, src: Tensor, axis: int,
            reduce: ScatterMode = ScatterMode.NONE) -> Tensor: ...


def Full(elem: Union[int, float, SymbolicScalar, Element], shape: List[int],
         valid_shape: Optional[List[Union[int, SymbolicScalar]]] = None) -> Tensor: ...


@overload
def Reshape(a: Tensor, shape: List[int], valid_shape: Optional[List[Union[int, SymbolicScalar]]] = None,
            inplace: bool = False) -> Tensor: ...


@overload
def Reshape(a: Tensor, shape: List[SymbolicScalar], inplace: bool) -> Tensor: ...


@overload
def Maximum(a: Tensor, b: Tensor) -> Tensor: ...


@overload
def Maximum(a: Tensor, b: Element) -> Tensor: ...


@overload
def Minimum(a: Tensor, b: Tensor) -> Tensor: ...


@overload
def Minimum(a: Tensor, b: Element) -> Tensor: ...


def Unsqueeze(a: Tensor, axis: int) -> Tensor: ...


def Expand(a: Tensor, shape: List[int], valid_shape: Union[List[Union[int, SymbolicScalar]]] = [
]) -> Tensor: ...


def Where(a: Tensor, b: Union[Tensor, Element], c: Union[Tensor, Element]) -> Tensor: ...


def Assign(a: Tensor) -> Tensor: ...


def QuantMX(input: Tensor, quantDtype: DataType = DataType.DT_FP8E4M3,
            mode: DequantScaleRoundingMode = DequantScaleRoundingMode.ROUND_DOWN,
            axis: int = -1, performanceMode: bool = True) -> Tuple[Tensor, Tensor]: ...


class MatmulExtendParam:
    @overload
    def __init__(self): ...

    @overload
    def __init__(self, bias_tensor: Tensor, scale_tensor: Tensor,
                 scale: int = 0, relu_type: ReLuType = ReLuType.NoReLu,
                 trans_mode: TransMode = TransMode.CAST_NONE): ...


@overload
def Matmul(dtype: DataType, a: Tensor, b: Tensor, a_trans: bool = False,
           b_trans: bool = False, c_matrix_nz: bool = False) -> Tensor: ...


@overload
def Matmul(dtype: DataType, a: Tensor, b: Tensor, a_trans: bool = False,
           b_trans: bool = False, c_matrix_nz: bool = False, extend_params: MatmulExtendParam = None) -> Tensor: ...


@overload
def MatmulMX(dtype: DataType, a: Tensor, aScale: Tensor, b: Tensor, bScale: Tensor, a_trans: bool = False,
             a_scale_trans: bool = False, b_trans: bool = False, b_scale_trans: bool = False,
             c_matrix_nz: bool = False) -> Tensor: ...

@overload
def MatmulMX(dtype: DataType, a: Tensor, aScale: Tensor, b: Tensor, bScale: Tensor, a_trans: bool = False,
             a_scale_trans: bool = False, b_trans: bool = False, b_scale_trans: bool = False,
             c_matrix_nz: bool = False, extend_params: MatmulExtendParam = None) -> Tensor: ...


@overload
def BatchMatmul(dtype: DataType, a: Tensor, b: Tensor, a_trans: bool = False,
                 b_trans: bool = False, c_matrix_nz: bool = False) -> Tensor: ...


@overload
def BatchMatmul(dtype: DataType, a: Tensor, b: Tensor, a_trans: bool = False, b_trans: bool = False,
                 c_matrix_nz: bool = False, extend_params: MatmulExtendParam = None) -> Tensor: ...


def BatchMatmulMX(dtype: DataType, a: Tensor, aScale: Tensor, b: Tensor, bScale: Tensor, a_trans: bool = False,
             a_scale_trans: bool = False, b_trans: bool = False, b_scale_trans: bool = False,
             c_matrix_nz: bool = False) -> Tensor: ...


@overload
def BatchMatmulMX(dtype: DataType, a: Tensor, aScale: Tensor, b: Tensor, bScale: Tensor, a_trans: bool = False,
             a_scale_trans: bool = False, b_trans: bool = False, b_scale_trans: bool = False,
             c_matrix_nz: bool = False, extend_params: MatmulExtendParam = None) -> Tensor: ...


@overload
def Assemble(a: List[Tuple[Tensor, List[SymbolicScalar]]], dst: Tensor,
             parallel: bool = False) -> None: ...


@overload
def Assemble(a: Tensor, offset: List[SymbolicScalar], dst: Tensor) -> None: ...


def AtomicRMW(src: Tensor, offsets: List[SymbolicScalar], dst: Tensor, mode: AtomicRMWMode) -> None: ...

# pass config
class PassConfigKey(enum.Enum):
    KEY_DUMP_GRAPH = ...


class PassConfigs:
    printGraph = ...
    dumpGraph = ...
    dumpPassTimeCost = ...
    preCheck = ...
    postCheck = ...
    disablePass = ...
    healthCheck = ...


def GetPassDefaultConfig(key: PassConfigKey, default_value: bool) -> bool: ...


def SetPassDefaultConfig(key: str, value: bool): ...


def GetPassConfig(strategy: str, identifier: str, key: PassConfigKey, default_value: bool) -> bool: ...


def SetPassConfig(strategy: str, identifier: str, key: PassConfigKey, value: bool): ...


def GetPassConfigs(strategy: str, identifier: str) -> PassConfigs: ...


def GetOptionsTree() -> str: ...


def LogTopFolder() -> str: ...


def ResetLog(path: str): ...


# distributed
class AtomicType(enum.Enum):
    SET = ...
    ADD = ...


class ShmemTensor:
    def __init__(self) -> None: ...
    group: str
    world_size: int
    data: Tensor
    signal: Tensor


def CreateShmemData(
    group: str,
    world_size: int,
    dtype: DataType,
    shape: List[int],
) -> ShmemTensor: ...

def CreateShmemData(
    group: str,
    world_size: int,
    dtype: DataType,
    shape: List[int],
    t: ShmemTensor,
) -> None: ...

def CreateShmemSignal(
    group: str,
    world_size: int,
) -> ShmemTensor: ...

def CreateShmemSignal(
    group: str,
    world_size: int,
    t: ShmemTensor,
) -> None: ...

def ShmemView(
    operand: ShmemTensor,
    shapes: List[int],
    offsets: Union[List[int], List[SymbolicScalar]],
) -> ShmemTensor: ...

def ShmemView(
    operand: ShmemTensor,
    shapes: List[int],
    new_valid_shapes: List[SymbolicScalar],
    new_offsets: List[SymbolicScalar],
) -> ShmemTensor: ...

def ShmemPut(
    src: Tensor,
    dst: ShmemTensor,
    dst_rank: SymbolicScalar,
    put_op: AtomicType,
    pred: Tensor,
) -> Tensor: ...

def ShmemGet(
    src: ShmemTensor,
    src_rank: SymbolicScalar,
    pred: Tensor,
    target_data_type: DataType = DataType.DT_BOTTOM,
) -> Tensor: ...

def ShmemSignal(
    dst: ShmemTensor,
    dst_rank: SymbolicScalar,
    notify_rank: SymbolicScalar,
    signal: int,
    sig_op: AtomicType,
    pred: Tensor,
) -> Tensor: ...

def ShmemSignalAll(
    dst: ShmemTensor,
    dst_rank: SymbolicScalar,
    signal: int,
    sig_op: AtomicType,
    pred: Tensor,
) -> Tensor: ...

def ShmemWaitUntil(
    src: ShmemTensor,
    src_rank: SymbolicScalar,
    cmp: OpType,
    cmp_value: int,
    clear_signal: bool,
    pred: Tensor,
) -> Tensor: ...

def ShmemClearData(
    src: ShmemTensor,
    pred: Tensor,
) -> Tensor: ...

def ShmemClearSignal(
    src: ShmemTensor,
    pred: Tensor,
) -> Tensor: ...

def ShmemBarrier(
    src: ShmemTensor,
    pred: Tensor,
) -> Tensor: ...

def ShmemLoad(
    src: ShmemTensor,
    src_rank: SymbolicScalar,
    pred: Tensor,
    non_shmem_data_type: DataType = DataType.DT_BOTTOM,
) -> Tensor: ...

def ShmemStore(
    src: Tensor,
    dst: ShmemTensor,
    dst_rank: SymbolicScalar,
    put_op: AtomicType,
    pred: Tensor,
) -> Tensor: ...

def GetSymbolicScalarPeId(group: str) -> SymbolicScalar: ...


def Nop(in_tensors: List[Tensor]) -> Tensor: ...


def Uniform(key: Element, counter0: SymbolicScalar, counter1: Element, shape: List[int], rounds: Element, dtype: DataType = DataType.DT_FP32) -> Tensor: ...
